### ISSUE TITLE
Any plans to support DataGrid?

### ISSUE THREAD

**Issue by schwasam** [fsprojects/Avalonia.FuncUI#146]
Hi,

Are there any plans to support DataGrid?
I understand that it was experimental/alpha in Avalonia at some point, but is now available as a separate NuGet package (Avalonia.Controls.DataGrid).

Or what would be the alternative to use right now?

**Comment by JaggerJo** [comment]
Hey, 

Hmm, good question. When this was considered the last time there was no maintainer for the DataGrid implementation on the avalonia side and the API wasn't final IIRC.

I'm happy to take PR's that adds bindings for the DataGrid Control.

**Comment by AngelMunoz** [comment]
by the way, we also added a "Guide" on how to create bindings a few days ago
https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/guides/Bindings.html

In case someone wants to take a jab at this

**Comment by artipo** [comment]
I was looking into this issue, but saw @albert-du PR. What should we do?
In case `DataGrid` should not be included in Avalonia.FuncUI maybe this issue should be closed.

Thanks.

**Comment by schwasam** [comment]
Yes from reading the PR comments it looks like DataGrid doesn't work well with F#/immutability.
Closing it.
