### ISSUE TITLE
[Question] How to create TreeView with non-recursive datastructure

### ISSUE THREAD

**Issue by NicoVIII** [fsprojects/Avalonia.FuncUI#154]
Hi everyone!

I tried to create a TreeView with a non-recursive datastructure but I couldn't figure out how to do it with Avalonia.FuncUI.
I looked at this article for default Avalonia with XAML:
https://www.nequalsonelifestyle.com/2019/06/18/avalonia-treeview-tutorial/#adding-more-hierarchy

Here they define multiple "TreeDataTemplates" with different DataTypes and ItemsSources to provide a hierarchical structure. The examples I found for FuncUI are only for a recursive datatype.
It looks like I can't use DataTemplateView, because of the type constraints of the itemsSelector function.

Is it easily possible to use TreeView with non-recursive datastructures with FuncUI?

**Comment by JaggerJo** [comment]
should be but there currently is a bug in the data template. 

It should be something that's easy to fix - I encourage you to take a look at https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/a9f9ac8040cc4f5df9cfbc846d5ca60303784074/src/Avalonia.FuncUI/Components/DataTemplateView.fs#L36-L67

**Comment by NicoVIII** [comment]
Thanks!
I will try to understand what happens there and if I can make it work, I'll create a PR.

**Comment by NicoVIII** [comment]
I created a PR which extends the DataTemplate to allow non-recursiveness. #156

I'm still not sure how to use that with the TreeView though. As far as I can see it is not easily possible to define multiple datatemplates for one control, I can only use the ItemTemplateProperty to set one.
Is there already a way to do that which I didn't see?

**Comment by NicoVIII** [comment]
I don't need this anymore, so I close this for now.
