### ISSUE TITLE
how does one test views?

### ISSUE THREAD

**Issue by zhangzhen** [fsprojects/Avalonia.FuncUI#159]
Testing desktop apps is not so easy. Does Avalonia.FuncUI provides the testing support for views as Fabulous does?

Zhen

**Comment by AngelMunoz** [comment]
Hello there, I regarding the update function I think we follow the same approach you can see a small guide here
https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/guides/Unit-Testing-Avalonia-FuncUI-Apps.html

but regarding the view I think unless @JaggerJo knows if we have helpers like those mentioned [here](https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/testing.html#testing-view)

**Comment by JordanMarr** [comment]
Closing this issue as it appears to be abandoned. 
feel free to reopen if you still need help.
