### ISSUE TITLE
IView vs IView<'a> is annoying

### ISSUE THREAD

**Issue by B-Reif** [fsprojects/Avalonia.FuncUI#161]
It's often useful to create functions that accept an `IView` as a child. This allows developers to use the same 'outer' view like a box or overlay, with different content inside. `IView` includes two definitions, a non-generic `IView` and a generic `IView<'a>`.

Because `children` (and similar properties) accept overloads, it's impossible to do this without some type annotations and casting:

```fs
// Reusable overlay function
let overlay child =
    Border.create [
        Border.classes [ "rw-modal" ]
        Border.child child // Error: A unique overload for method 'child could not be determined based on type information prior to this program point. A type annotation may be needed.
    ]
```

This causes multiple problems. First, it's inconvenient to provide an explicit type annotation for such a simple function. Second, annotating one casting of `IView` prevents using the function for the other type. The only way around this presently is to invoke `Helpers.generalize` for almost every view function in the application, or to write adapter functions. Either way, this adds a lot of boilerplate to the DSL.

In my usage of FuncUI, I have no reason to inspect the content of a view value. If I want to compose changes to a view, I do list operations on the `IAttr list` before passing the result to `create`.

After that, the framework uses the view's innards to diff and patch. Everything inside of the `IView` value is an implementation detail of FuncUI. The framework should expose a single, opaque `View` type to the developer.

**Comment by uxsoft** [comment]
What's the difference between `IView` and `IView<unit>`?

**Comment by JaggerJo** [comment]
> What's the difference between `IView` and `IView<unit>`?

The generic version is used to make the DSL type safe. 
The non generic version is used internally.

This should be resolved by targeting .NET 6 I think.
