### ISSUE TITLE
Responding to keyboard events

### ISSUE THREAD

**Issue by bisen2** [fsprojects/Avalonia.FuncUI#162]
I was wondering if there is a way to use keyboard events to call the update method in this framework. I looked through the documentation and examples and didn't see anything related to this. Thanks!

**Comment by jl0pd** [comment]
Hello, I've done this with subscription adapted it from Game of life example [here](https://github.com/fsprojects/Avalonia.FuncUI/blob/89fe4aaf62ed7cc710105f1bac90e82d6eda7917/src/Examples/Examples.GameOfLife/Program.fs#L20).

You can find working program [here](https://github.com/jl0pd/Snake) (and link to code sample [here](https://github.com/jl0pd/Snake/blob/4f94452fba51b8102dbff4a7e97575c7c4b99de2/Program.fs#L23)). It was my first FuncUI program so many things may have been done wrong.
```fsharp
        let keyDownHandler _ =
            let sub dispatch =
                this.KeyDown.Add (fun eventArgs ->
                    match eventArgs.Key with
                    | Key.Up -> Game.Message.Up
                    | Key.Down -> Game.Message.Down
                    | Key.Left -> Game.Message.Left
                    | Key.Right -> Game.Message.Right
                    | Key.Space -> Game.Message.Pause
                    | Key.F2 -> Game.Message.NewGame
                    | _ -> Game.Message.Empty
                    |> dispatch)
                |> ignore
            Cmd.ofSub sub
```

**Comment by bisen2** [comment]
Awesome, this worked perfectly for me. Thanks for the help!
