### ISSUE TITLE
Dependency Conflict Doesn't Allow Build

### ISSUE THREAD

**Issue by fourglobe302500** [fsprojects/Avalonia.FuncUI#164]
Sorry if I misstype some things as english is not my mother language

Hi I just used the quick start template, and during a simple clean up of code (to make with my likying) and saw it didn't restore by itself to pick-up the necessary references and did the restore, but it didn't restore the Test project, so I transfered to paket to see if it would correct itself but it didn't, instead it gave me back this error

```
     Resolved packages:
      - Avalonia.Desktop 0.9.7
      - Expecto 8.0.0
      - Expecto.VisualStudio.TestAdapter 10.0.0
      - FSharp.Core 4.7.0
      - FSharp.Data 3.3.3
      - JaggerJo.Avalonia.FuncUI 0.4.0
      - JaggerJo.Avalonia.FuncUI.DSL 0.4.0
      - JaggerJo.Avalonia.FuncUI.Elmish 0.4.0
      - Microsoft.NET.Test.Sdk 16.0.0
      - Microsoft.TestPlatform.TestHost 16.0.0
      - YoloDev.Expecto.TestSdk 0.1.0
     Conflict detected:
      - Expecto.VisualStudio.TestAdapter 10.0.0 requested package Microsoft.TestPlatform.ObjectModel: >= 15.0 < 16.0
      - Microsoft.TestPlatform.TestHost 16.0.0 requested package Microsoft.TestPlatform.ObjectModel: >= 16.0
```

I tried adding '>= 16.0', '>= 15.0 < 16.0' and '>= 15.0' to the 'Microsoft.TestPlatform.ObjectModel' to resolve the dependency issue but it keeped running in a loop for about 5 min in each case

Is there any way around this issue? Did I do something wrong? I really want to make this project and can't start becouse of this.
But either way thanks in advance for even taking your time reading this (most likely awfull piece of text)

**Comment by FoggyFinder** [comment]
Have you found out a solution/workaround for this issue?

**Comment by fourglobe302500** [comment]
@FoggyFinder no, but just because I had some other issues at the time but I already known of a possibility that can work, which is simple remove the test library and make a new one. (and I have a hunche that this problem is either on the expecto library itself or the version of dotnet at the time since most of the librarys where finishing migrating to net5.0)
