### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by Ferryry** [fsprojects/Avalonia.FuncUI#169]
I encountered an issue:

> System.MissingMethodException: "Method not found: 'Void Avalonia.IAvaloniaObject.SetValue(Avalonia.AvaloniaProperty`1<!!0>, !!0, Avalonia.Data.BindingPriority)'."

I have installed the following packages:
Avalonia
Elmish
FSharp.Core
Avalonia.FuncUI
Avalonia.FuncUI.DSL
Avalonia.FuncUI.Elmish

![error](https://user-images.githubusercontent.com/88947587/129963726-64766a27-8357-4e5a-bee9-36e06977b582.jpg)

**Comment by FoggyFinder** [comment]
I can't check it by myself at this moment but my guess you're using wrong version of Avalonia. Try to set an explicit version starting from `0.10.0` and then updating it one by one if needed until this exception is thrown.

**Comment by TheFernode** [comment]
I am using the Version `0.10.7` of Avalonia and the latest version of Avalonia.FuncUI from GitHub.

**Comment by jl0pd** [comment]
FuncUI version 4.x requires Avalonia 9.x. If you want to use Avalonia 10.x then you need to use FuncUI 5.x.
