### ISSUE TITLE
Avalonia MVU - a must, for C#

### ISSUE THREAD

**Issue by najak3d** [fsprojects/Avalonia.FuncUI#171]
C# is far more widely used than F#. .  Sure would like to see Avalonia MVU working with C#.

I see work stopped on this about a year ago, with it left in Beta.   Is this usable for a production App?

(I'm assuming not...  ???)

**Comment by JaggerJo** [comment]
This Library heavily relies on F# ability to create custom DSLs. This is used to specify all views. 

The core logic (differ, patcher) should just work with F#.

Development lost traction as I no longer have the time to maintain this. It it usable, and a small community keeps it up to date now.

Full C# support is and was never planned.

**Comment by najak3d** [comment]
Thank you for the response JaggerJo.  That's unfortunate.   IMO, since Avalonia itself is not so MVU-friendly, that's going to hurt it's potential to grab market-share of users.

Our interest is in finding and helping to promote the "winner".  One of our key goals is to import "MVU-style professional GUI's" into the Gaming World.   Already, we have Avalonia integrated into Urho3D -- it renders to a 2D texture on screen -- and allows us to inject user inputs back to Avalonia...  so it's an awesome solution.  But is XAML/MVVM-centric in nature.

So when we found your MVU-based solution, this looked very promising.

===
Next up - we're investigation the capacity for MAUI to render to a Bitmap and allows Input injection (same as we're doing now with Avalonia).   If we can get this to work -- most likely MAUI will become or "silver-bullet" solution for "Game GUI's" -- as MAUI seems to be "really doing things rights" -- offering both XAML/MVVM and MVU  (via "Comet") solutions as first-class citizens.   MAUI's focus on adding MVU support is a key to their success.

Thank you for your good work here!  I think you had the "right idea" for sure.

**Comment by dsyme** [comment]
@JaggerJo If it's ok I'd like to post an bisdue abd tweet calling for new maintainers? I'd actually be interested myself too, as a backup maintainer - I always find engaging with MVU projects helps push the F# lang design along

**Comment by JaggerJo** [comment]
@dsyme would be great! I'm always willing to help, just don't have the time to properly maintain the library.

**Comment by najak3d** [comment]
> @JaggerJo If it's ok I'd like to post an issue and tweet calling for new maintainers, with you in guidance role? I'd actually be interested myself too, as a backup maintainer - I always find engaging with MVU projects helps push the F# lang design along

Wow, *the* Don Syme is here?  F# was an ingenious invention.   Your involvement here might help promote the more widespread usage of Avalonia MVU.

I see MAUI.Fabulous appears to be the F# branch of MAUI, to bring this genius to the MAUI world.

One of the best aspects of working OpenSource is getting to bump elbows with "greatness" (i.e. folks like you).

**Comment by dsyme** [comment]
Closing this in favour of https://github.com/fsprojects/Avalonia.FuncUI/issues/172

**Comment by JordanMarr** [comment]
> Thank you for the response JaggerJo. That's unfortunate. IMO, since Avalonia itself is not so MVU-friendly, that's going to hurt it's potential to grab market-share of users.
> 
> Our interest is in finding and helping to promote the "winner". One of our key goals is to import "MVU-style professional GUI's" into the Gaming World. Already, we have Avalonia integrated into Urho3D -- it renders to a 2D texture on screen -- and allows us to inject user inputs back to Avalonia... so it's an awesome solution. But is XAML/MVVM-centric in nature.
> 
> So when we found your MVU-based solution, this looked very promising.
> 
> === Next up - we're investigation the capacity for MAUI to render to a Bitmap and allows Input injection (same as we're doing now with Avalonia). If we can get this to work -- most likely MAUI will become or "silver-bullet" solution for "Game GUI's" -- as MAUI seems to be "really doing things rights" -- offering both XAML/MVVM and MVU (via "Comet") solutions as first-class citizens. MAUI's focus on adding MVU support is a key to their success.
> 
> Thank you for your good work here! I think you had the "right idea" for sure.

Nobody does C# MVU better than @shirshov (see his C# Xamarin.Forms MVU library, [Laconic](https://github.com/shirshov/laconic)). He is an fsharper stuck in csharp land, so he brings MVU to C#.

**Comment by najak3d** [comment]
> Nobody does C# MVU better than @shirshov (see his C# Xamarin.Forms MVU library, [Laconic](https://github.com/shirshov/laconic)). He is an fsharper stuck in csharp land, so he brings MVU to C#.

At a glance, looks like he's augmenting Xamarin Forms from the outside, to effectively create MVU behavior.  Since XF itself is laggy, I'm guessing that his solution likewise is subject to this same lagginess.

Lucky for Xamarin MVU lovers, MAUI is creating MVU solution as a first-class citizen, that should run without lag.   His presentation of MAUI Comet (MVU) is here.  I've got high hopes for Comet:

https://www.youtube.com/watch?v=9kwrgm_-FCk
