### ISSUE TITLE
Seeking new co-maintainers for Avalonia.FuncUI

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Avalonia.FuncUI#172]
@JaggerJo is seeking new co-maintainers for Avalonia.FuncUI

This is an important project for the F# ecosystem and is listed as the No 1 option for "Use F# for Desktop Apps" in https://fsharp.org/use/desktop-apps/.  It is usable, stable and with low bug counts, and with good engineering practices.  

I'm interested in doing some backup co-maintenance myself, and will be keeping an eye on things. 

Please let us know if you're interested in becoming co-maintainer here.

Many thanks!

for @JaggerJo, @sergey-tihon and myself

**Comment by sleepyfran** [comment]
Hey Don! Thanks for bringing this up and for the ping on the upgrade PR 😃 

I'd love to help with the maintenance, I'd probably not have time to be a full-on maintainer but I can definitely help with reviews, upgrades and some new features.

**Comment by dsyme** [comment]
Fantastic!  I will make you co-maintainer - reviews, upgrades, looking after PRs etc is what we're after for sure

* Policies for fsprojects maintainers are [here](https://github.com/fsprojects/fsprojects-admin#an-f-community-project-incubation-space), take a quick glance, I think you know the gig

* You'll be added to the "maintainers" group and I'll send an announcement there

**Comment by dsyme** [comment]
Cool thanks. We should likely move to auto-publish during main branch build (that's what FSharp.Data and several other "fsprojects" projects are doing)

**Comment by dsyme** [comment]
And welcome @sleepyfran as a new co-maintainer! Great to have you on board :)

**Comment by JaggerJo** [comment]
> > And welcome @sleepyfran as a new co-maintainer! Great to have you on board :)
> 
> Thank you Don! Will definitely take a look soon and update whatever's needed 😃

Nice! Happy to help if something comes up @sleepyfran. Automating releases seems like a good first step to simplify maintenance.

**Comment by houstonhaynes** [comment]
I'd love to pitch in but I have quite a bit of woodshedding/headscratching to do in this department. I planned on using Avalonia for a WSL monitor project so it's right up my alley, but I won't be very useful until I've had some time with it. That said if you're willing to take on someone who needs a bit of "runway" to get acclimated I'd be happy to pitch in. 👍

**Comment by unbyte** [comment]
Wow, I'm so glad to see this project has new maintainers! I gave up using F# to implement GUI before because I've encountered some problems and found that this library has fallen far behind the development progress of Avalonia.
I don't know much about the dotnet and F# community now (my open-source activities focus on the web community), but I'm interested in contributing to (not maintaining) this project.

**Comment by sleepyfran** [comment]
@dsyme @JaggerJo what's the procedure to be able to edit NuGet packages? I see the packages from this repo belong to the `fsprojects` org, but I'm not sure how to request access to it 😄

**Comment by dsyme** [comment]
@sleepyfran Let me know if you need more help with that

**Comment by JordanMarr** [comment]
> Wow, I'm so glad to see this project has new maintainers! I gave up using F# to implement GUI before because I've encountered some problems and found that this library has fallen far behind the development progress of Avalonia. I don't know much about the dotnet and F# community now (my open-source activities focus on the web community), but I'm interested in contributing to (not maintaining) this project.

Would you mind listing some of the major areas you see where this library has fallen behind Avalonia? (Asking for me. 😅)

**Comment by unbyte** [comment]
> Would you mind listing some of the major areas you see where this library has fallen behind Avalonia? 

Version😂. One thing I can remember is transparent windows are supported in Avalonia 0.10+, but Avalonia.FuncUI is not compatible with Avalonia 0.10+.

**Comment by Texl** [comment]
@dsyme @JaggerJo I'd love to help maintain this library. I've been using F# professionally for a few years now but have only recently had the opportunity to add in some GUI - I've been having a great time with FuncUI so far. My public Github record is pretty light, though - to start I'll look to contribute via some PRs first.

**Comment by sleepyfran** [comment]
Closing this since I think we're good so far 😃 But anyone who wants to contribute please do, PRs are very welcomed indeed!
