### ISSUE TITLE
Consider renaming packages

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Avalonia.FuncUI#173]
The packages currently use "JaggerJo.Avalonia.ABC" naming.  This should probably be renamed to "Avalonia.ABC" or "AvaloniaCommunity.ABC"

https://www.nuget.org/packages?q=avalonia+funcui

**Comment by sleepyfran** [comment]
I think this would be a very good thing to do before we publish the first new version to avoid future upgrade problems.

**Comment by sleepyfran** [comment]
Also important to note if we do end up renaming the packages: we should update the getting started docs to reflect the new names, probably good to tackle as part of #174

**Comment by JordanMarr** [comment]
"Avalonia.FuncUI.ABC" seems like a good choice to me.

**Comment by jl0pd** [comment]
Nuget for some time have [prefix preservation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation) that forbids packages from anyone to be in form `System.ABC` or `Avalonia.ABC`. Because of this package have to be named FuncUI.Avalonia or we have to get access to this prefix by avalonia team. Most chose first option, e.g. Dock.Avalonia, MessageBox.Avalonia, Citrus.Avalonia and Live.Avalonia

**Comment by JordanMarr** [comment]
There is always "FSharp.Avalonia" since that is used by some of the other fsprojects.

**Comment by JaggerJo** [comment]
> Nuget for some time have [prefix preservation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation) that forbids packages from anyone to be in form `System.ABC` or `Avalonia.ABC`. Because of this package have to be named FuncUI.Avalonia or we have to get access to this prefix by avalonia team. Most chose first option, e.g. Dock.Avalonia, MessageBox.Avalonia, Citrus.Avalonia and Live.Avalonia

Talked to @grokys about this years ago. At the time Avalonia was still in early beta (or maybe even alpha). FuncUI was an early prototype. Getting a 'sub prefix' permission on NuGet seems to be possible, but a bit of work/ writing mails back and forth. So it was too much effort at the time, that's why they are prefixed with `JaggerJo` if I remember correctly.

**Comment by sleepyfran** [comment]
Revisiting this conversation now that we're ready to release a new version 😃

@dsyme, @JordanMarr, @JaggerJo do we have consensus over any name? And also: any extra steps needed to rename the packages other than changing the names in the `.fsproj` files? Missing if there's something needed on the NuGet side since I've never published anything there.

**Comment by JaggerJo** [comment]
> Revisiting this conversation now that we're ready to release a new version 😃
> 
> @dsyme, @JordanMarr, @JaggerJo do we have consensus over any name? And also: any extra steps needed to rename the packages other than changing the names in the `.fsproj` files? Missing if there's something needed on the NuGet side since I've never published anything there.

I like `FSharp.Avalonia.FuncUI` but don't really care too much. I think just renaming it in the `fsproj` files is enough.

**Comment by grokys** [comment]
I think that at this point, if you wanted to move FuncUI to the Avalonia org and use our CI/publish infrastructure we could call it `Avalonia.FuncUI`? @danwalmsley what do you think?

**Comment by JaggerJo** [comment]
> I think that at this point, if you wanted to move FuncUI to the Avalonia org and use our CI/publish infrastructure we could call it `Avalonia.FuncUI`? @danwalmsley what do you think?
> 
> Of course that would be completely up to you - I totally understand if you want to keep it separate.

Would be the best name IMHO, but moving the repo out of the `fsprojects` org might not be the best idea as the F#  community keeps to project alive. 

@grokys Would it be possible to keep the project in the `fsprojects` community incubator and grant us a [prefix subset reservation delegation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) for `Avalonia.FuncUI`?

**Comment by sleepyfran** [comment]
> Would be the best name IMHO, but moving the repo out of the `fsprojects` org might not be the best idea as the F# community keeps the project alive. @JordanMarr @sleepyfran opinions?
> 
> @grokys Would it be possible to keep the project in the `fsprojects` community incubator and grant us a [prefix subset reservation delegation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) for `Avalonia.FuncUI`?

Agree that having `Avalonia.FuncUI` name while keeping the repo here would be the best move, I think this org gives a great chance of discovery for F# projects 😃

**Comment by grokys** [comment]
> @grokys Would it be possible to keep the project in the fsprojects community incubator and grant us a [prefix subset reservation delegation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) for Avalonia.FuncUI?

Ah! I don't think this was possible the last time we spoke about this. Yep, that sounds like a good idea.

>But moving the repo out of the fsprojects org might not be the best idea as the F# community keeps the project alive. 

Yep, that shouldn't be a problem if the subset delegation works.

I'll discuss this with the rest of the core team and get that done!

**Comment by JaggerJo** [comment]
> > @grokys Would it be possible to keep the project in the fsprojects community incubator and grant us a [prefix subset reservation delegation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) for Avalonia.FuncUI?
> 
> Ah! I don't think this was possible the last time we spoke about this. Yep, that sounds like a good idea.
> 
> > But moving the repo out of the fsprojects org might not be the best idea as the F# community keeps the project alive.
> 
> Yep, that shouldn't be a problem if the subset delegation works.
> 
> I'll discuss this with the rest of the core team and get that done!

Thanks a lot!

**Comment by danwalmsley** [comment]
If you guys want to let's make it happen! Make Avalonia one big family. It's pretty clear that FuncUI is an important part of avalonia now, you have all proven that 👍😁

**Comment by sleepyfran** [comment]
> If you guys want to let's make it happen! Make Avalonia one big family. It's pretty clear that FuncUI is an important part of avalonia now, you have all proven that 👍😁

Thanks a lot! @danwalmsley @grokys what are the next steps to make this possible? From what I see in the NuGet you need to grant us the prefix access, is there any action needed from our side? 😃
