### ISSUE TITLE
Check getting-started instructions

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Avalonia.FuncUI#174]
Since we're going over things, it's probably worth the time to check the getting-started instructions are correct and working, starting with the links at

https://fsharp.org/use/desktop-apps/

and in the README.

**Comment by AngelMunoz** [comment]
This might be relevant, we had some initial attempt to have documentation for this,
https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs
it was made with fornax, but even if we don't use the whole thing, there may be some material that can be re-used in the form of markdown files

**Comment by AngelMunoz** [comment]
The links work, but I think the templates have outdated dependencies, I had one draft PR to update them before I got busy with other things it's likely to be outdated as well

**Comment by dsyme** [comment]
> This might be relevant, we had some initial attempt to have documentation for this, https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs

Was there a reason to have docs in a separate repo? Also what are the tradeoffs between having this repo in "fsprojects" and "AvaloniaCommunity"?

**Comment by AngelMunoz** [comment]
I think at the time the main reasoning was to have a "_cleaner_" repository for the the main library  but it doesn't need to be that way as far as I remember :) the same story applies with the templates as well I think.

The docs could be merged into the main repository along with the templates, I'm not sure what is the default solution for documentation in the fsprojects organization but it that is/gets set up, I can ensure that we can migrate those markdown files as needed here

**Comment by dsyme** [comment]
> I think at the time the main reasoning was to have a "cleaner" repository for the the main library but it doesn't need to be that way as far as I remember :) the same story applies with the templates as well I think.

OK thanks - that explains the separation of the docs into a separate project, though I was also wondering what the story was for this repo itself (Avalonia.FuncUI) moving from "AvaloniaCommunity" to "fsprojects".


> The docs could be merged into the main repository along with the templates, I'm not sure what is the default solution for documentation in the fsprojects organization but it that is/gets set up, I can ensure that we can migrate those markdown files as needed here

Yes, the docs should go into a "docs" directory and we should likely use "fsdocs" here like in other repos.  Though maybe with different styling - I know it's important for UI tech to have really good and fresh styling in their docs.

**Comment by JaggerJo** [comment]
> Yes, the docs should go into a "docs" directory and we should likely use "fsdocs" here like in other repos. Though maybe with different styling - I know it's important for UI tech to have really good and fresh styling in their docs.

Yeah, would be nice to have `fsdocs` in place. Moving the docs & templates to different repositories was a mistake.

**Comment by JaggerJo** [comment]
The new docs have been updated.
