### ISSUE TITLE
Problem with scrollbar

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#186]
I'm trying to get an app to show a scrollbar, but I can't figure out how it's supposed to be done. 

The code is essentially:
`    StackPanel.create [

        StackPanel.children [

            ScrollViewer.create [ 

                ScrollViewer.verticalScrollBarVisibility Primitives.ScrollBarVisibility.Visible ;

                ScrollViewer.content (

                    StackPanel.create [

                        StackPanel.children [

                            // STUFF HERE

                        ]

                    ] 

                )

            ] ;

        ]

    ]     `

The view shows a scrollbar to the right, but it's not allowing any scrolling, even if the content becomes bigger than the window. Is there anything obvious I'm doing wrong?

**Comment by JaggerJo** [comment]
Not something that I immediately recognise. Can you create a minimal reproduction? (like a single file a can run?)

**Comment by arnesahlberg** [comment]
That would be very helpful. Here is a quick example:
[Gui.zip](https://github.com/fsprojects/Avalonia.FuncUI/files/7940877/Gui.zip)

**Comment by JaggerJo** [comment]
Can't build the attached project, but looks fine. 

There are big upcoming changes to FuncUI (see PR below). I'd recommend you to check out that branch so you can use the latest version of Avalonia + other cool stuff. Will be released soon.

https://github.com/fsprojects/Avalonia.FuncUI/pull/179

**Comment by arnesahlberg** [comment]
Weird... for me it builds alright.

Anyway, for me it just becomes a list of textbooks that goes beyond the window, but the scrollbar doest work. 

<img width="399" alt="Skärmavbild 2022-01-26 kl  11 53 51" src="https://user-images.githubusercontent.com/7228271/151150748-01756e02-a110-4dca-9ee2-1cfb4656fe54.png">

Looking forward to the new changes. Will try the one you showed.

**Comment by JaggerJo** [comment]
You could try using a dock panel as the top-level control / or a scroll viewer directly. I think your code will just work with the latest version of avalonia.

**Comment by arnesahlberg** [comment]
Hey! With a DockPanel it actually worked. 

I assume the new version is not released as a package yet, and I have to build it myself?

**Comment by JordanMarr** [comment]
> I assume the new version is not released as a package yet, and I have to build it myself?

Yes, but it's sooo close to being released!
