### ISSUE TITLE
Proper use of DataTemplateView to add close button to tabs.

### ISSUE THREAD

**Issue by marekhilton** [fsprojects/Avalonia.FuncUI#187]
I've been trying to implement a very simple close button on a tab control. To do this I've been using the `DataTemplateView` class transform the header into a name and a button. I attach a function that dispatches the a `Close` message and the tab's GUID as a tuple. The tab with the respective GUID is then removed from the list of tabs. The individual tab is implemented in the module `Page` with it's respective `State`, `Msg`, `update`, and `view`:

```
module Page =

    let private tabView closeFunc (name:string) =
        let components =
            DockPanel.create [
                DockPanel.children [
                    Button.create [ Button.dock Dock.Right
                                    Button.content "x"
                                    Button.onClick closeFunc ]
                    TextBlock.create [ TextBlock.text name
                                       TextBlock.dock Dock.Left]
                    ]
                ]
        Border.create [ Border.child components ]

    let tabHeader closeFunc =
        tabView closeFunc
        |> DataTemplateView<string>.create

    type State =
        { uid : System.Guid }

    type Msg =
        | Noop
        | Close

    let init uid =
        { uid = uid }

    let update (msg:Msg) (state:State) =
        match msg with
        | Noop -> state
        | _ -> printfn "SHOULD NOT HAPPEN" ; state


    let view (state:State) dispatch : Avalonia.FuncUI.Types.IView =
        let content = TextBox.create [TextBox.text "Hello"]
        let closeFunc (_:'a) =
            dispatch Close
        TabItem.create
            [
                TabItem.header (state.uid.ToString().Substring(0,4))
                TabItem.headerTemplate (tabHeader closeFunc)
                TabItem.content content
            ]

```

The main part of the program is implemented in `Shell`. Each page is an element in a list contained in the top level state. In the `update` function I use `List.filter` to remove the page with the GUID specified in the the message.

```
module Shell =

    type State =
        { devicePages : Page.State list }

    type Msg =
        | Msg of System.Guid * Page.Msg

    let init =
        { devicePages = List.map (fun _ -> {uid = System.Guid.NewGuid()} ) [0..3] },
        Cmd.none

    let update (msg: Msg) (state: State): State * Cmd<_> =
        match msg with
        | Msg (uid,Page.Msg.Close) ->
            {state with devicePages = List.filter (fun st -> st.uid <> uid) state.devicePages},
            Cmd.none
        | Msg (_,_) ->
            state, Cmd.none

    let view (state: State) dispatch =
        let deviceDispatch uid msg =
            Msg(uid,msg) |> dispatch

        TabControl.create
                [ TabControl.classes ["shell"]
                  TabControl.tabStripPlacement Dock.Top
                  TabControl.viewItems
                      [ yield! List.map (fun st -> Page.view st (deviceDispatch st.uid)) state.devicePages ]
                ]
```

However, this doesn't seem to work. I can close tabs if I work from right to left (from the end of the list to the root) but if I try to work from the left to the right then I get "stuck" tabs that don't want to close. For example, if I have four tabs, if I close the first one then I will have three tabs but I won't be able to close the tab that is now in the first position. Have I misused the `DataTemplateView` class or is there a more fundamental problem?

I've omitted some of the code for brevity. A full working project can be found at: https://github.com/marekhilton/TabTestIssue

**Comment by JaggerJo** [comment]
First thought would be that the following might fix it. 

Functions/Delegates don't support equality so FuncUI does not know if it needs to patch the `onClick` handler. 

```fsharp
..
Button.create [
    Button.dock Dock.Right
    Button.content "x"
    Button.onClick (closeFunc, SubPatchOptions.OnChangeOf name) 
]
..
```

I'd recommend you to take a look at the [PR branch ](https://github.com/fsprojects/Avalonia.FuncUI/pull/179). Will be merged soon and makes building apps a lot simpler.

**Comment by marekhilton** [comment]
By the way I forgot to say thank you making such an awesome project!

I thought it would be probably be something to do with functions not supporting equality. But using `SubPatchOptions.OnChangeOf` or `SubPatchOptions.Always` doesn't seem to make a difference.

I will check out that branch, looks exciting!
