### ISSUE TITLE
SaveFileDialog issue?

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#190]
I'm trying to open a save-dialog. In the update-function I call:

```
| SaveButton -> state, 

        let dialog = SaveFileDialog () in

        dialog.Title <- "Save file" ; 

        dialog.DefaultExtension <- ".json" ; 

        dialog.Directory <- Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) ;

        let showDialog window = dialog.ShowAsync(window) |> Async.AwaitTask in

        Cmd.OfAsync.perform showDialog window AfterSaveFileSelected

| AfterSaveFileSelected path -> printfn "%s" path ; state, Cmd.none // just to check if the filepath is correctly selected
```

As I try to open the dialog, I get an odd error message though. Seems like something to do with AppKit. Is this a Mac-issue? Is there something I'm doing wrong?

Error message:

`-[NSSavePanel _initBridgeAndStuff] caught non-fatal NSInternalInconsistencyException 'assertion failed: '-[NSRemoteView _preSuperInit] has been invoked on a thread which is incompatible with AppKit; the problem is likely in a much shallower frame in the backtrace' in -[NSRemoteView _preSuperInit] on line 2372 of file /System/Volumes/Data/SWE/macOS/BuildRoots/5b2e67f8af/Library/Caches/com.apple.xbs/Sources/ViewBridge/ViewBridge-638.3/NSRemoteView.m' with backtrace (
......
`

**Comment by JaggerJo** [comment]
Run the code above on the UI thread using the [Dispatcher](http://reference.avaloniaui.net/api/Avalonia.Threading/Dispatcher/).

**Comment by arnesahlberg** [comment]
I see. I don't know how to use the dispatcher, really. Is there some simple example?

Ps. I tried to run the initial code on a Windows pc, and it works there. So seems like a Mac-related issue.

**Comment by FoggyFinder** [comment]
> I see. I don't know how to use the dispatcher, really. Is there some simple example?

See #128
