### ISSUE TITLE
Problem when removing elements - redraw GUI from model?

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#191]
I have an issue I don't know how to solve.

I have a list of content in a model, represented in UI elements. If I click a button to remove one piece of content in the modeland hence the corresponding UI element, the contents and UI elements that come after it in a list gets mixed up, presumably because Avalonia believes believes the other fields have changed. 

Is there some way of telling Avalonia to redraw the interface completely after an element has been removed?

**Comment by JaggerJo** [comment]
If you already use the new components stuff (I would recommend that) you can simply change the component key.

What exactly gets mixed up?

**Comment by arnesahlberg** [comment]
For example, I click here to remove an element:
<img width="234" alt="Skärmavbild 2022-02-15 kl  09 40 16" src="https://user-images.githubusercontent.com/7228271/154024651-48b867b2-7c91-4ca0-9c3e-5916e86fbcab.png">

I expect it to just remove the one element I click on, however it ends up looking like this:
<img width="227" alt="Skärmavbild 2022-02-15 kl  09 40 36" src="https://user-images.githubusercontent.com/7228271/154024707-c32ea655-994d-41c3-8f4b-16b7fa4b4a8f.png">

I can see that the model is correct following the click, i.e. just the element I click on is removed. However, UI thinks I changed some values and dispatches some events.


Where can I read about the new component stuff?

**Comment by FoggyFinder** [comment]
@arnesahlberg can you provide [MRE](https://software.codidact.com/posts/285810/285811#answer-285811)? Maybe there is a bug in FuncUi or Avalonia but I do have app with "remove" item option and it works flawlessly.

**Comment by FoggyFinder** [comment]
Looks like a bug indeed. Can't say what's wrong there - I have no time to check source code to attempt to understand root of this behavior.

But that's not how I'd expect to use StackPanel. Instead I suggest using of `ScrollViewer` + `ItemsControl`.
Something like that

```fs
let elementBlock (kvi:KeyValuePair<string, string>) dispatch =
    Expander.create [
        Expander.header kvi.Value
        Expander.isExpanded true
        Expander.content (
            StackPanel.create [
                StackPanel.children [
                    TextBox.create [
                        TextBox.text kvi.Value
                        TextBox.onTextChanged ((fun x -> 
                            if kvi.Value <> x then SetText (kvi.Key, x) |> dispatch
                        ), SubPatchOptions.Always)
                    ]
                    Button.create [
                        Button.content "Remove element"
                        Button.onClick (fun _ -> 
                            RemoveElement kvi.Key |> dispatch
                        )
                    ]
                ]
            ]
        )
    ] :> IView

let view (state: State) (dispatch) =
    let addButton = 
        Button.create [
            Button.content "Add content"
            Button.onClick (fun _ -> 
                dispatch AddElement
            )
        ]

    StackPanel.create [
        StackPanel.children [
            ScrollViewer.create [
                ItemsControl.create [
                    ItemsControl.dataItems state.elements
                    ItemsControl.itemTemplate(
                        DataTemplateView<KeyValuePair<string, string>>.create(fun kvp -> 
                            elementBlock kvp dispatch
                        )
                    )
                ]
                |> ScrollViewer.content
            ]
            addButton
        ]
    ]  
```

not sure I kept the initial logic though

**Comment by arnesahlberg** [comment]
Thanks for the suggestion. Will try something like this! Hopefully it will work better.

**Comment by JaggerJo** [comment]
@arnesahlberg interesting - just checked your code (haven't had a chance to run it) and it looks fine.

I recommend to build and use the code on master - contains a lot of fixes, new programming models, ... but is not released yet.

**Comment by arnesahlberg** [comment]
@JaggerJo Yeah, I thought it would work as I wrote it. But will probably move over to using ItemsControl for now, since this seems to solve the problem. 

Will likely use 0.5 for my next project. Starting another thing soon, but the one I'm working on now is almost completed.

**Comment by arnesahlberg** [comment]
@FoggyFinder One more question. Right now I have "nested" items, so inside this ItemsControl I will have another set of ItemsControls (and a few more layers). Here I have a problem, since the nested ones don't get updated in the GUI until I change the outer layer. Is there some way of making sure nested ItemsControl get updated as well?

Or maybe I should just migrate to the newer version?

**Comment by JaggerJo** [comment]
> @FoggyFinder One more question. Right now I have "nested" items, so inside this ItemsControl I will have another set of ItemsControls (and a few more layers). Here I have a problem, since the nested ones don't get updated in the GUI until I change the outer layer. Is there some way of making sure nested ItemsControl get updated as well?

No idea TBH, there might be an error in the differ. It should just work. 

> Or maybe I should just migrate to the newer version?

That's what I would recommend. It also includes a new `Components/State handling` model that's more like react. This makes bigger apps a lot faster as the differ only runs on affected components - instead of everything. 

Updating should be painless.

**Comment by arnesahlberg** [comment]
@JaggerJo 

Actually, I'm having some trouble running the Elmish examples just out of the box. I get the error message
<img width="1903" alt="Skärmavbild 2022-02-16 kl  10 26 19" src="https://user-images.githubusercontent.com/7228271/154234952-7f15cd59-e3a0-4a63-add0-ef592b20d3c0.png">
Is there some reason for this?

The component examples run fine, though.

**Comment by arnesahlberg** [comment]
@JaggerJo

Is there any plan on making FuncUI compatible with net6? I have some dependencies in my next project that require net6.

**Comment by JaggerJo** [comment]
> @JaggerJo
> 
> Is there any plan on making the new version of FuncUI compatible with net6? I have some dependencies in my next project that require net6.

should just work.

**Comment by FoggyFinder** [comment]
> Right now I have "nested" items, so inside this ItemsControl I will have another set of ItemsControls (and a few more layers). Here I have a problem, since the nested ones don't get updated in the GUI until I change the outer layer

@arnesahlberg can you share code? I'm almost certain I have app with nested components and it works with no issues

**Comment by arnesahlberg** [comment]
Will try to fix an MRE tomorrow. May not share the entire code because it's a company thing.

**Comment by arnesahlberg** [comment]
@JaggerJo 

Here is a short example of the problem I'm having. 
[MRE.zip](https://github.com/fsprojects/Avalonia.FuncUI/files/8086803/MRE.zip)

If I click the "Add element" button, I get a new element. If I, however, click the "Add deeper element" button inside an element nothing happens. Until I add another outer element. Then all the deeper elements appear.

**Comment by FoggyFinder** [comment]
> Here is a short example of the problem I'm having.
> [MRE.zip](https://github.com/fsprojects/Avalonia.FuncUI/files/8086803/MRE.zip)

@arnesahlberg you can't expect it to work properly with mutable fields inside records. That's just wrong most of the time. So I'm not going to check why it doesn't work here :-)

Try something like this

```fs
    type State = { count : int ; elements : Map<string, Element> ; update : int  }
    and Element = {
        Name : string ;
        Elements : Map<string, Element>
    }

    let createElement name =
        {
            Name = name ;
            Elements = Map []
        }

    let init = { count = 0 ; elements = Map [] ; update = 0 }

    type Msg = 
        | SetElementName of string * string 
        | RemoveElement of string
        | AddElement 
        | AddDeeperElement of string
        | SetDeeperElementName of string * string * string
        | RemoveDeeperElement of string * string

    let update (msg: Msg) (state: State) : State =
        printfn "%A" msg 
        match msg with
        | SetElementName (key,value) -> 
            let elements = 
                state.elements
                |> Map.add key { state.elements.[key] with Name = value }
            {state with update = state.update + 1; elements = elements }
        | RemoveElement ( key) -> {state with elements = state.elements.Remove key}
        | AddElement -> {state with elements = state.elements.Add(sprintf "el:%i" state.count, createElement <| sprintf "new %i" state.count) ; count = state.count+1}
        | AddDeeperElement key -> 
            let k = sprintf "el:%i" state.count
            let v = createElement <| sprintf "deeper element %i" state.count
            let elements = 
                state.elements
                |> Map.add key { state.elements.[key] with Elements = state.elements.[key].Elements.Add(k,v) }
            { state with count = state.count + 1; elements = elements }
        | RemoveDeeperElement (key, dKey) -> 
            let elements = 
                state.elements
                |> Map.add key { state.elements.[key] with Elements = state.elements.[key].Elements.Remove dKey }
            { state with count = state.update + 1; elements = elements }
        | SetDeeperElementName (key, dkey, value) -> 
            let inner = 
                state.elements.[key].Elements
                |> Map.add dkey { state.elements.[key].Elements.[dkey] with Name = value }
            let elements = 
                state.elements
                |> Map.add key { state.elements.[key] with Elements = inner }
            { state with count = state.update + 1; elements = elements }
```

**Comment by arnesahlberg** [comment]
@FoggyFinder Really? I see.

Thanks.
