### ISSUE TITLE
Getting the window icon working (MacOS)

### ISSUE THREAD

**Issue by Evelios** [fsprojects/Avalonia.FuncUI#194]
I've been trying to figure out how to get my gui's window icon to register within the system dock within MacOS. I would like to get it working on all platforms, however I wasn't sure if there were extra quirks to MacOS that I was missing. This also seems like a good thing that could be added to the examples and templates for reference for people picking up the project for the first time.

`Shell.fs`
```fsharp
type MainWindow() as this =
    inherit HostWindow()

    do
        base.Title <- "Title"
        base.Width <- 600
        base.Height <- 400
        base.Icon <- WindowIcon "avares://Gui/Assets/Icon.ico"
        this.HasSystemDecorations <- true
```

`Gui.fsproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <AvaloniaResource Include="**\*.xaml" />
        <AvaloniaResource Include="Assets\*.ico" />
    </ItemGroup>

    ...

</Project>
```

I had also tried this without success

```fsharp
type MainWindow() as this =
    inherit HostWindow()
    do
        base.Icon <- WindowIcon "Assets/Icon.ico"
```
```xml
        <None Include="Assets\*" CopyToOutputDirectory="PreserveNewest" Link="Assets" />
```

**Comment by iminashi** [comment]
For macOS I believe you need to create an app bundle that includes an .icns icon for it to work.

[https://docs.avaloniaui.net/docs/distribution-publishing/macos](https://docs.avaloniaui.net/docs/distribution-publishing/macos)

**Comment by Evelios** [comment]
@iminashi Thanks, this seems to be the right road to go down. I tested my previous attempts on Linux and I'm able to get the icon working. I haven't gotten it working on Mac yet but I anticipate that with some more work and the Avalonia publishing guide, I should get there
