### ISSUE TITLE
TextBox KeyDown event

### ISSUE THREAD

**Issue by cnelson04-beckman** [fsprojects/Avalonia.FuncUI#197]
Currently the KeyDown event does not catch keys like back, left, right. I have been creating a behavior that implements a mask capability, and so have to catch the Key.Back event. Because I have to catch this in the KeyUp I get a flash where see the back delete the previous character. Seems like the KeyDown should catch all key presses, not just specific ones.

**Comment by JaggerJo** [comment]
FuncUI just exposes the Avalonia events. Some controls handle certain keypresses internally.

Check the different event phases, you probably want to hook into 'tunneled' events instead of 'bubbled' ones.
