### ISSUE TITLE
Can Canvas receive onKeyDown or onTextInput?

### ISSUE THREAD

**Issue by nickgravgaard** [fsprojects/Avalonia.FuncUI#201]
I'm trying to write a program which shows different bits of text at various coordinates in the window depending on what the user types into it. In some ways what I want to make is similar to a game - I need to draw things on the screen and receive keyboard events (and eventually mouse ones too). I've attempted to do this by making a Canvas with functions defined for onKeyDown/onTextInput, but they don't seem to get run. Am I doing anything wrong? Is there another way of doing this? Thanks.

**Comment by FoggyFinder** [comment]
have you found suitable solution?

**Comment by JordanMarr** [comment]
Closing this issue as it seems to be abandoned. 
Feel free to reopen if needed.
