### ISSUE TITLE
Component model OpenFileDialog

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#206]
I'm trying to use the new component model for a desktop app and I can't figure out how to get an OpenFileDialog working.

I'm trying like this, and I do get a dialog, but it freezes as soon as I try to interact with it.

```
let d = OpenFileDialog()
d.Title <- "Select file"
d.AllowMultiple <- false
let a = d.ShowAsync window |> Async.AwaitTask |> Async.RunSynchronously
```

Any advice?

**Comment by jl0pd** [comment]
Simply don't wait task synchronously. Elmish architecture is asynchronous in it's core and uses messages to change state. Let task complete and then dispatch message about selection. I'm not sure how to do it right with components though.

```fsharp
let selectFileAsync () =
    task {
        let dlg = OpenFileDialog(
                    AllowMultiple = false,
                    Filters = ResizeArray [
                                FileDialogFilter(
                                    Name = "Solution file",
                                    Extensions = ResizeArray [ "sln" ])
                    ])

        let! files = dlg.ShowAsync(getMainWindow())
        if files.Length > 0 then
            return FileSelected files.[0]
        else
            return FileNotSelected
    } |> Cmd.OfTask.result
```

https://github.com/jl0pd/LightSolutionConfigurationManager/blob/master/src/LightSolutionManager/MainView.fs#L48-L63

**Comment by AngelMunoz** [comment]
@jl0pd the OP asked for the component model introduced in v0.5.0 this is different to elmish

@arnesahlberg I made a quick sample here https://github.com/AngelMunoz/WindowSample

The relevant lines are
- https://github.com/AngelMunoz/WindowSample/blob/main/Program.fs#L16
- https://github.com/AngelMunoz/WindowSample/blob/main/Counter.fs#L15-L43

basically the idea is just to make window available and do a "fire and forget" style of call


```fsharp

let view (window: Window) =

    Component(fun ctx ->
        let filePaths = ctx.useState []

        let handleClickAsync () =
            let dialog = OpenFileDialog()
            dialog.AllowMultiple <- true

            let filter =
                FileDialogFilter(Extensions = List<string>([ "md" ]), Name = "Markdown Files")

            dialog.Filters.Add(filter)
            dialog.Title <- "Select Markdown Files"

            async {
                let! files = dialog.ShowAsync window |> Async.AwaitTask
                files |> Seq.toList |> filePaths.Set
            }

        let handleClickTask () =
            let dialog = OpenFileDialog()
            dialog.AllowMultiple <- true

            let filter =
                FileDialogFilter(Extensions = List<string>([ "md" ]), Name = "Markdown Files")

            dialog.Filters.Add(filter)
            dialog.Title <- "Select Markdown Files"

            task {
                let! files = dialog.ShowAsync window
                files |> Seq.toList |> filePaths.Set
            }
    StackPanel.create [(* ... children ... *)])
```
I also left both task/async so you can choose which ever you feel is better for you, the differences are insignificant in this case as this is not performance sensitive
```fsharp
Button.create
    [
        Button.content "Open Dialog Using Async"
        Button.onClick (fun _ -> handleClickAsync () |> Async.Start)
    ]
Button.create
    [
        Button.content "Open Dialog Using Task"
        Button.onClick (fun _ -> handleClickTask () |> ignore)
    ]
```

**Comment by arnesahlberg** [comment]
Thank you this works!

For some reason the async-version causes an 'NSInternalInconsistencyException' and crashes on my Mac, while the task-version works fine.
