### ISSUE TITLE
the Examples.Elmish.MusicPlayer uses an incorrect URI 

### ISSUE THREAD

**Issue by newbienewbie** [fsprojects/Avalonia.FuncUI#209]
According to the [Avalonia docs of Referencing assets](https://docs.avaloniaui.net/docs/getting-started/assets#referencing-assets), we should use  assembly name instead of namespace after the `avares://`.

So this line 
https://github.com/fsprojects/Avalonia.FuncUI/blob/abe8a54919a893ed7181a54daa09fccf2fee7776/src/Examples/Elmish%20Examples/Examples.Elmish.MusicPlayer/Program.fs#L14

should be changed to
```f#
this.Styles.Load "avares://Examples.Elmish.MusicPlayer/Styles.xaml"
```

And the same goes for 

https://github.com/fsprojects/Avalonia.FuncUI/blob/abe8a54919a893ed7181a54daa09fccf2fee7776/src/Examples/Elmish%20Examples/Examples.Elmish.MusicPlayer/Shell.fs#L158

and 

https://github.com/fsprojects/Avalonia.FuncUI/blob/abe8a54919a893ed7181a54daa09fccf2fee7776/src/Examples/Elmish%20Examples/Examples.Elmish.MusicPlayer/Shell.fs#L163

**Comment by OscarFKE** [comment]
Just came across this problem myself, I can confirm that the proposed changes work

**Comment by FoggyFinder** [comment]
@newbienewbie would you like to open PR with these changes?
