### ISSUE TITLE
Quickstart Template missing

### ISSUE THREAD

**Issue by scottbot95** [fsprojects/Avalonia.FuncUI#210]
_Not sure if this is really most appropriate here or on [the docs repo](https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs), but given the docs repo has no issues, I opted to create this here._

With the update to 0.5.0 which merged the templates into this repo from [AvaloniaCommunity/Avalonia.FuncUI.ProjectTemplates](https://github.com/AvaloniaCommunity/Avalonia.FuncUI.ProjectTemplates). Unfortunately as part of that transition, it appears the QuickStart template got left behind. This template is still heavily mentioned in the docs and is referenced as the recommended template to use for creating a new project.

Either the docs referencing the quick start template should be removed to complete the purge of that template, or the template should be restored. It seems to be that either direction is acceptable (especially since the QuickStart used Expecto which seems to be more-or-less unmaintained so it would require updates to be compatible with any modern version of .NET), but half removing the QuickStart template is a very awkward state to be in.

**Comment by AngelMunoz** [comment]
Hey there, sorry for the late response, the reason I didn't port back the quick-start template is because it was quite big to move and update to the new component style

I guess we should look into removing it from the docs or have someone to port it over to the new component model + the mvu (the way it is right now)

**Comment by JaggerJo** [comment]
Think this can be closed, the new docs make it quite simple to start a new app. 

https://funcui.avaloniaui.net
