### ISSUE TITLE
Investigate how we can remove the IView/IView<'> situation in inline components

### ISSUE THREAD

**Issue by sleepyfran** [fsprojects/Avalonia.FuncUI#223]
With the introduction of inline components in #220 I couldn't find a way to properly accept only `IView<Inline>` for the `inlines` property of the `RichTextBlock`. It's not a big deal, but it could be great if we could fix this to first of all avoid passing wrong props to the component and also to get rid of the needed `:> IView` cast in the first inline component.

**Comment by JaggerJo** [comment]
I've also looked into this and there is no solution apparently (that I'm aware of).
