### ISSUE TITLE
OpenFileDialog fail on macOS - running on UI thread doesn't fix it

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#230]
I'm trying to open an OpenFileDialog, and in issue [228](https://github.com/fsprojects/Avalonia.FuncUI/issues/228) I got the tip to run it on the UI thread using the dispatcher. 

I'm trying to do this, but it still doesn't work. The code I used previously (without the Dispatcher) worked on macOS 15, but not since upgrading to 16. 

Perhaps I'm using the Dispatcher incorrectly. Posting the code here:

```
let openFile window (state : IWritable<ViewModel>) =

    let openFileTask = 
        Dispatcher.UIThread.InvokeAsync(fun () ->
            System.Func<System.Threading.Tasks.Task<string[]>>(fun () ->
                let dialog = OpenFileDialog() in
                dialog.AllowMultiple <- false;
                dialog.Title <- "Select document" ;
                dialog.ShowAsync window
            ))
        in

    task {
        let! filesFunc = 
            openFileTask 
            |> Async.AwaitTask
            in
        let! files = 
            filesFunc.Invoke()  
            |> Async.AwaitTask
            in
        match files |> Array.tryHead with
        | Some file -> 
            let doc = ViewModel.LoadFile file in
            state.Set doc
        | None -> ()
    } |> ignore
```

**Comment by Numpsy** [comment]
Do you have too many layers of delegates there? (it looks like it might be using ```UIThread.InvokeAsync``` to execute a function that returns a task, and then executing that task outside of the dispatcher scope?

The original issue suggesting dispather use looks more like
```fsharp
    let openFileTask = 
        Avalonia.Threading.Dispatcher.UIThread.InvokeAsync<string[]>(
            System.Func<System.Threading.Tasks.Task<string[]>>(fun () ->
                let dialog = OpenFileDialog() in
                dialog.AllowMultiple <- false;
                dialog.Title <- "Select document" ;
                dialog.ShowAsync(null)
            ))
        in
```

The only mac I have access to is an old x86 one on Catalina so I can't try it myself (I have a test app on that that's opening a file  dialog from a menu event without using the dispatcher at all, but I have no idea how much things have changed here in newer versions)

**Comment by arnesahlberg** [comment]
Thanks for the help. It seems better like this. I still don't get it working, though.

If I pass null to dialog.ShowAsync it's doesn't do anything, and if I pass it the window it gives the same error as before.

**Comment by Numpsy** [comment]
Are you using the latest Avalonia libs, just in case any of the macOS fixes over there have effected anything? (I think FuncUI 0.5.x is a couple of versions behind the latest)

**Comment by arnesahlberg** [comment]
I use Avalonia.Desktop 0.10.18, which I think is the latest. 

I can see the File dialog window open, but as soon as I move my mouse over it it crashes.

**Comment by JordanMarr** [comment]
Closing because issue seems to be abandoned. Feel free to reopen if you still need help.
