### ISSUE TITLE
11.0.0-preview4 vs. RichTextBlock

### ISSUE THREAD

**Issue by Numpsy** [fsprojects/Avalonia.FuncUI#232]
I just tried to update an application that was using Avalonia 11.0.0-preview3 to the new 11.0.0-preview4 build and got a bunch of errors from FuncUI about ```RichTextBlock``` not existing.

I had a look at the Avalonia change history and saw https://github.com/AvaloniaUI/Avalonia/pull/9245 which seems to have renamed the control

**Comment by JaggerJo** [comment]
@Numpsy interesting 🤨

Would you mind creating a PR that aligns naming?

Otherwise it might take a bit until it's fixed.

**Comment by Numpsy** [comment]
I'll have a look later

**Comment by Numpsy** [comment]
I started to have a look, and then fell over another breaking Avalonia change in #233 

Another related thing as well - version 11 of Avalonias Blazor integration has been retargetted against .NET 7.0, so I think the web assembly playground app will need changing to match

**Comment by sleepyfran** [comment]
Closed in #234
