### ISSUE TITLE
ScrollViewer turns its content controls into text

### ISSUE THREAD

**Issue by marklam** [fsprojects/Avalonia.FuncUI#235]
I might be doing something wrong, but if I put controls inside a `ScrollViewer`'s `content`, I get a string version of the controls instead of the controls themselves.

eg:
https://github.com/fsprojects/Avalonia.FuncUI/compare/master...marklam:Avalonia.FuncUI:scrollviewer-repro

![image](https://user-images.githubusercontent.com/1962640/201761435-20df8417-1ed4-4013-9225-adff22232593.png)

**Comment by JaggerJo** [comment]
You are (accidentally) using the `obj` overload.

`ScrollViewer.content` expects a single view, not a list. 

        static member content<'t when 't :> ContentControl>(value: IView) : IAttr<'t> =

**Comment by marklam** [comment]
Thanks, I get it now!
