### ISSUE TITLE
Counter template bin folder size

### ISSUE THREAD

**Issue by konst-sh** [fsprojects/Avalonia.FuncUI#241]
Hi, I'm new to desktop apps, and was exploring basic counter project template and there are two things that I'm concerned about:
- when making build in release mode I'm having bin folder size of ~120MB. I guess that the simple counter app cannot be this big or I'm wrong?
- when running this app (build in release mode) the debug console window is opened as well.
Any ideas?

**Comment by JaggerJo** [comment]
Hi @konst-sh,

Avalonia.FuncUI is just a thin wrapper on top of AvaloniaUI. I'd recommend raising your question [here](https://github.com/AvaloniaUI/Avalonia).
