### ISSUE TITLE
JaggerJo.Avalonia.FuncUI --> Avalonia.FuncUI

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Avalonia.FuncUI#242]
@JordanMarr Any chance we could get the pacakges renamed from `JaggerJo.Avalonia.FuncUI` --> `Avalonia.FuncUI`?

**Comment by JaggerJo** [comment]
@dsyme would really like to do this, but the `Avalonia` package prefix is reserved on Nuget.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/13090415/211408856-f11e7ab7-6b9f-4842-a43d-54b46d79740a.png">

Aparrently it is possible to delegate permission of a certain prefixes (`Avalonia.FuncUI.*`).

There was a previous discussion about this [here](https://github.com/fsprojects/Avalonia.FuncUI/issues/173). Seems like the Avalonia Team is on board.

@danwalmsley @grokys would it be possible to get prefix delegation setup? Or were there any issues last time we need to resolve?

**Comment by JaggerJo** [comment]
**Update:** I've reached out to the Avalonia Team and we found a simpler solution. The FsProjects NuGet account should have received a ownership invitation.

@JordanMarr @sleepyfran does either of you have access to that account?

**Comment by sleepyfran** [comment]
> @JordanMarr @sleepyfran does either of you have access to that account?

I don't have access, I believe @dsyme should have it since he was the one that added us to the project here. 

Thanks for moving forward with this! 😃

**Comment by JordanMarr** [comment]
What did you have to do to get the package uploaded?

![image](https://user-images.githubusercontent.com/1030435/213324353-29525606-3efb-4ab0-a78d-b71ed0c43771.png)

**Comment by JaggerJo** [comment]
I sent the prebuilt packages to the Avalonia Team. This was so they could upload the packages and then add me and fsprojects as owners on nuget. 

Publishing should just work, but apparently the fsprojects nugget account did not accept the invitation or something.

@dsyme there should be an invitation sent to the fsprojects account, but none of us has access. Could you approve it?

**Comment by JaggerJo** [comment]
@JordanMarr @sleepyfran added my nuget key for now. works: https://github.com/fsprojects/Avalonia.FuncUI/actions/runs/3960134318

**Comment by JordanMarr** [comment]
Nice! I love that it has the official check mark now! 
We should probably delist the old packages once the new ones are out of pre-release.
