### ISSUE TITLE
How do I update the docs?

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/Avalonia.FuncUI#260]
I'm referring to the new ones here: https://funcui.avaloniaui.net/

(Not the old ones, here: https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/)

**Comment by sleepyfran** [comment]
@JordanMarr I just saw that when the Avalonia folks initially created the page they only invited Josua, Angel and me. Send me your email over a DM on Mastodon and I'll invite you as well 😃 

Once you have access, logging into your account in GitBook shows the editor.
