### ISSUE TITLE
Is it possible on freebsd?

### ISSUE THREAD

**Issue by devosalain** [fsprojects/Avalonia.FuncUI#280]
I have installed :
mono-5.10.1.57_3               Open source implementation of .NET Development Framework
&
fsharp-10.2.1                  Functional and object-oriented language for the .NET platform

I can run fsharpc & mono but i have no dotnet executable.

**Comment by JaggerJo** [comment]
Hi 👋

good question. I think the first step is to get .NET Core itself working. (seems like you [can build it from source](https://github.com/sec/dotnet-core-freebsd-source-build) for free BSD).

I'm not sure if AvaloniaUI itself runs on Free BSD as it's not officially supported. I guess you'd have to try it.

**Comment by devosalain** [comment]
What i did :
Installed a pre-compiled "dotnet-sdk-6.0.101-freebsd-x64.tar.gz"
The following line worked:
dotnet new --install JaggerJo.Avalonia.FuncUI.Templates
The following line worked:
dotnet new funcui.basic -n NewApp
cd NewApp
dotnet run

This returns error:
/usr/home/x/dotnet2/NewApp/NewApp.fsproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/FSharp/library-packs, nuget.org
The build failed. Fix the build errors and run again.

**Comment by JaggerJo** [comment]
Interesting. This is an issue related to running dotnet on free BSD. I'd raise an issue in the dotnet runtime repository.

**Comment by devosalain** [comment]
With
<TargetFramework>net6.0</TargetFramework>
dotnet run
Error:
```
/usr/home/x/my_dotnet/NewApp/NewApp.fsproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64 with version (= 6.0.9)
/usr/home/x/my_dotnet/NewApp/NewApp.fsproj : error NU1102:   - Found 2 version(s) in nuget [ Nearest version: 6.0.11 ]
/usr/home/x/my_dotnet/NewApp/NewApp.fsproj : error NU1102:   - Found 0 version(s) in /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/FSharp/library-packs
/usr/home/x/my_dotnet/NewApp/NewApp.fsproj : error NU1102:   - Found 0 version(s) in nuget.org

The build failed. Fix the build errors and run again.
```

With
<TargetFramework>net6.0.11</TargetFramework>
dotnet run
Error:
```
/usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5): error NETSDK1073: The FrameworkReference 'Microsoft.NETCore.App' was not recognized [/usr/home/x/my_dotnet/NewApp/NewApp.fsproj]

The build failed. Fix the build errors and run again.
```

**Comment by JaggerJo** [comment]
I'm closing this issue as it's not related to FuncUI.
