### ISSUE TITLE
Bug in rendering nested selections

### ISSUE THREAD

**Issue by matthewcrews** [fsprojects/Avalonia.FuncUI#286]
I created a repo that demonstrates a bug that I cannot figure out. I'm reasonably confident the issue isn't with my code, but maybe I just don't understand the library.

Repo: https://github.com/matthewcrews/AvaloniaUIBug/tree/main

The UI is rendering a CheckBox as checked when it should not be.

**Comment by JaggerJo** [comment]
Hey @matthewcrews, thanks for the great repro - made it easy to test.

When you pass an `onClick` handler to a control that captures/has state you need to tell FuncUI when to patch it. This can be done by providing `SubPatchOptions` to the `onClick` attribute.

https://github.com/fsprojects/Avalonia.FuncUI/blob/e4b5503559908d18ddc5cac28a87741dea35c3fd/src/Avalonia.FuncUI/Builder.fs#L5-L11

You can avoid dealing with this mostly by creating a structure that aligns with view identity. View identity is determined by a few things (structure, type, key). I recommend checking out [this](https://funcui.avaloniaui.net/view-basics/lifetime) and [this](https://funcui.avaloniaui.net/components/component-lifetime).

`View.withKey` works well when things get complicated otherwise. (that's how I fixed it to ensure FuncUI behaves correctly)

Let me know if you have further questions / if something is unclear.

**Comment by JaggerJo** [comment]
Basically write code more that's like this:

```fsharp
let scenarioPickerView (state: IWritable<State>) =
    Component.create ("scenario", fun ctx ->
        let state = ctx.usePassed state

        StackPanel.create [
            StackPanel.spacing 10.0
            StackPanel.verticalAlignment VerticalAlignment.Top
            StackPanel.horizontalAlignment HorizontalAlignment.Left
            StackPanel.children [

                TextBlock.create [
                    TextBlock.text "Scenario Selection"
                ]

                CheckBox.create [
                    CheckBox.content "Baseline"
                    CheckBox.isChecked (state.Current.Scenario = Scenario.Baseline)
                    CheckBox.onClick (fun _ ->
                        state.Set  { state.Current with Scenario = Scenario.Baseline }
                    )
                ]

                CheckBox.create [
                    CheckBox.content "Expand"
                    CheckBox.isChecked (
                        match state.Current.Scenario with
                        | Scenario.Expand _ -> true
                        | _ -> false
                    )
                    CheckBox.onClick (fun _ ->
                        state.Set { state.Current with Scenario = Scenario.Expand (None, []) }
                    )
                ]

            ]
        ]
    )
```

**Comment by matthewcrews** [comment]
How does that interact with the `Window` type, though? This example is leaving out the thing that is hard which is passing the reference to the `Window` type so I can get a `Select File` dialog. I'm also unsure of how to connect this new view function to the `MainWindow`? Sorry for the dumb questions.

**Comment by matthewcrews** [comment]
Also, the example provided looks like a sibling component per this doc:
https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs/blob/master/src/guides/Hooks.md

That's not the scenario I'm dealing with, so I'm struggling to figure out how to hook this up.

Am I supposed to wrap this component in another component? It seems like that should be unnecessary, yes?

**Comment by matthewcrews** [comment]
I tried using the `Component.create` function and embedding that in another `Component` and adding `SubPatchOption.Always` to every `onClick` function, but I still got the same result. I'm missing something really important because when I debug, the state variable has the right values, but the render is wrong.

Branch: https://github.com/matthewcrews/AvaloniaUIBug/tree/subpatchoption-everything

**Comment by JaggerJo** [comment]
> I tried using the `Component.create` function and embedding that in another `Component` and adding `SubPatchOption.Always` to every `onClick` function, but I still got the same result. I'm missing something really important because when I debug, the state variable has the right values, but the render is wrong.
> 
> Branch: https://github.com/matthewcrews/AvaloniaUIBug/tree/subpatchoption-everything

I think I was a bit unclear about how I'd fix it. `SubPatchOptions` are an option, but not the one I'd pick as it's more complicated than just that in your case. 

# State can get mixed up by side effects if you don't account for them

FuncUI can only manage state to a certain level. If a CheckBox is checked and you don't mirror that action in your state you get detached from reality. FuncUI only diffs its previous state with the current one, but it does not actually compare what is set on a control.

A `CheckBox` sets it's internal state to checked/unchecked automatically when you click it. It's a side effect of the control. This is fine, but you need to mirror it in your state (`onChecked` & `onUnchecked`).

```fsharp
    let view () =
        Component (fun ctx ->
            let state = ctx.useState false

            DockPanel.create [
                DockPanel.children [
                    CheckBox.create [
                        CheckBox.isChecked state.Current
                        CheckBox.content "Checkbox A"
                        CheckBox.onChecked (fun _ -> state.Set true)
                        CheckBox.onUnchecked (fun _ -> state.Set false)
                    ]

                    CheckBox.create [
                        CheckBox.isChecked state.Current
                        CheckBox.content "Checkbox B"
                    ]
                ]
            ]
        )
```

![CleanShot 2023-03-24 at 11 04 14](https://user-images.githubusercontent.com/13090415/227491579-4b25f1ea-0df1-49ad-9ffd-5b43301f8de3.gif)

# Backing controls get reused, which makes it even worse



```fsharp
    [<Preview>]
    let view () =
        Component (fun ctx ->
            let showOptionB = ctx.useState false

            StackPanel.create [
                StackPanel.margin 10
                StackPanel.children [

                    CheckBox.create [
                        CheckBox.isChecked showOptionB.Current
                        CheckBox.content "Show option 'B'"
                        CheckBox.onChecked (fun _ -> showOptionB.Set true)
                        CheckBox.onUnchecked (fun _ -> showOptionB.Set false)
                    ]

                    CheckBox.create [
                        CheckBox.content "Checkbox A"
                    ]

                    if showOptionB.Current then
                        CheckBox.create [
                            CheckBox.content "Checkbox B"
                        ]

                    CheckBox.create [
                        CheckBox.content "Checkbox C"
                    ]
                ]
            ]
        )
```

![CleanShot 2023-03-24 at 11 15 47](https://user-images.githubusercontent.com/13090415/227494241-f210480c-29e9-48d6-8e44-5b6292a8839e.gif)

So how do we fix this?

## Option 1: Don't change the structure or your view hierarchy. If you need to hide a view do it with `isVisible`:

```fsharp
CheckBox.create [
    CheckBox.isVisible showOptionB.Current
    CheckBox.content "Checkbox B"
]
```

## Option 2: Explicitly state view identity using `View.withKey`/`View.createWithKey`:

```fsharp
CheckBox.create [
    CheckBox.isChecked showOptionB.Current
    CheckBox.content "Show option 'B'"
    CheckBox.onChecked (fun _ -> showOptionB.Set true)
    CheckBox.onUnchecked (fun _ -> showOptionB.Set false)
]

View.createWithKey "A" CheckBox.create [
    CheckBox.content "Checkbox A"
    CheckBox.onClick (fun _ -> printfn "clicked on Checkbox A")
]

if showOptionB.Current then
    View.createWithKey "B" CheckBox.create [
        CheckBox.content "Checkbox B"
        CheckBox.onClick (fun _ -> printfn "clicked on Checkbox B")
    ]

View.createWithKey "C" CheckBox.create [
    CheckBox.content "Checkbox C"
    CheckBox.onClick (fun _ -> printfn "clicked on Checkbox C")
]
```

**Comment by JaggerJo** [comment]
> Also, the example provided looks like a sibling component per this doc: https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs/blob/master/src/guides/Hooks.md
> 
> That's not the scenario I'm dealing with, so I'm struggling to figure out how to hook this up.
> 
> Am I supposed to wrap this component in another component? It seems like that should be unnecessary, yes?

From the previouse comment above you might already guess it. I recommend to do this for structure / view hierarchy.

**Comment by JaggerJo** [comment]
There should be better / more documentation on this, but it's hard to explain in text. I guess a short video would make a big difference.

**Comment by konst-sh** [comment]
This whole thread is worth to copy into documentation

**Comment by JaggerJo** [comment]
@matthewcrews is you issue resolved? / can I close this?

**Comment by matthewcrews** [comment]
Yes, thank you.
