### ISSUE TITLE
Styles.Load member is not available

### ISSUE THREAD

**Issue by ostapsivko** [fsprojects/Avalonia.FuncUI#290]
Hello team!

I've been trying to do some simple stuff, using provided samples as a foundation.

There's an issue with styling, basically I can't get it to work. I am trying to customize a ListBox to display an image as well as a text block inside one item.

For example, if I'll use the following inside the Styles.xaml, the view of the listbox with classes [ "folder" ] won't change it's appearance:

> <Styles xmlns="https://github.com/avaloniaui"  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
	<ListBox>
		<ListBox.Styles>
			<Style Selector="ListBox.folder">
				<Setter Property="ItemTemplate">
					<ItemTemplate>
						<Border CornerRadius="3" Padding="5" Background="Azure">
							<StackPanel Orientation="Horizontal">
								<Image Source="{SvgImage Assets/Icons/folder.svg}"/>
								<TextBlock Text="{Binding}"/>
							</StackPanel>
						</Border>
					</ItemTemplate>
				</Setter>
			</Style>
		</ListBox.Styles>
	</ListBox>	
</Styles>

I've noticed that in [this sample](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Examples/Elmish%20Examples/Examples.Elmish.Presso/) `Styles.Load` [method was used on the line 34](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Examples/Elmish%20Examples/Examples.Elmish.Presso/Program.fs).

However, if I'll try to use the same method, I'll get FS0039 error which tells me that this member is not available:
![image](https://user-images.githubusercontent.com/71553225/229925620-4a9b0456-bb5b-475b-ac11-759b80db77bf.png)

Now, the samples are using project references instead of the nuget packages, so I am not sure if this is related to some kind of a breaking changes caused by the recent updates or something else.

My packages are the following:
![image](https://user-images.githubusercontent.com/71553225/229925946-5591ad53-2665-46f4-a8ed-d73583470068.png)

Could you please take a look and let me know what am I doing wrong here? Any tips/hints/advices are much appreciated.

P.S. Thanks for your tremendous work on FuncUI!

**Comment by Numpsy** [comment]
Should be picked up from https://github.com/fsprojects/Avalonia.FuncUI/blob/1cdf7a6a241279c98e7b0b2ca1cea6e98b1cb170/src/Avalonia.FuncUI/Helpers.fs#L17 I think? (though there does appear to be a duplicate copy of the function in the control catalog app as well)

**Comment by ostapsivko** [comment]
Hello @Numpsy

You're right, I've missed to open Avalonia.FuncUI module. For some reason VS did not propose it.

Appreciate your help!
