### ISSUE TITLE
Theme property

### ISSUE THREAD

**Issue by melursus23** [fsprojects/Avalonia.FuncUI#294]
Hello,

How can I set the "Theme" property using your library?

I'm trying to mimic something similar to this but there is no `Border.theme` : 

```
<Border Theme="{StaticResource CardBorder}">
    <TextBlock>Card</TextBlock>
</Border>
```

https://github.com/irihitech/Semi.Avalonia/blob/922afa904b36b4b70669d9156e4f570bfffaebf4/demo/Semi.Avalonia.Demo/Pages/BorderDemo.axaml

**Comment by JaggerJo** [comment]
Seems like the `theme` does not have a binding yet. We should definitely add that, feel free to create a PR.

**Comment by melursus23** [comment]
Sure, I can try for sure.

Right now, I was able to add the following function:

```
        static member theme<'t when 't :> Layoutable>(theme: ControlTheme) : IAttr<'t> =
            AttrBuilder<'t>.CreateProperty<ControlTheme>(Layoutable.ThemeProperty, theme, ValueNone)
```

However, I'm not sure I've found the cleanest / easiest way to retrieve the theme resource, any suggestions?

`Border.theme ((ctx.control.FindResource("CardBorder")) :?> ControlTheme)`

**Comment by JaggerJo** [comment]
Nice 👍

Dealing with resources that need to be looked up is always a bit hairy. Having a control that's described with the following code also means that the `FindResource` is called every time a component/view is diffed. 

```fsharp
Border.create [
    Border.theme ((ctx.control.FindResource("CardBorder")) :?> ControlTheme)
]
```

Another way of setting the theme would be: 

```fsharp
Border.create [
    Border.init (fun border -> 
        border.Theme <- ((ctx.control.FindResource("CardBorder")) :?> ControlTheme)
    )
]
```

If you create a PR I'll merge the binding you created. 👍

**Comment by Numpsy** [comment]
> ```
> static member theme<'t when 't :> Layoutable>(theme: ControlTheme) : IAttr<'t> =
>             AttrBuilder<'t>.CreateProperty<ControlTheme>(Layoutable.ThemeProperty, theme, ValueNone)
> ```

Would ```StyledElement.ThemeProperty``` work and be more generic, assuming https://github.com/AvaloniaUI/Avalonia/blob/532e89c837d61d37d7fb2273f852d51bdc0f1999/src/Avalonia.Base/StyledElement.cs#L75 is the 'base' definition? (Layoutable being a subclass of StyledElement?)

**Comment by melursus23** [comment]
@JaggerJo thanks for the suggestion, make sense to use the init! I was thinking at maybe creating a centralized place when all styles are defined and available. I don't really like the fact that right now I'm relying of a string a well, maybe a TypeProvider could be created for the purpose, but this is way to far from my current f# knowledge :) 

@Numpsy make sense, I've made the suggested change!

In all cases, PR created :)

**Comment by Numpsy** [comment]
> maybe a TypeProvider could be created for the purpose

There have been attempts at xaml type providers before (e.g. https://github.com/fsprojects/FsXaml) but I don't know about usage with Avalonia (I once made one attempt at an F# WPF project using the type provider for generating bindings from xaml and couldn't get it to work, and that's about the limit of my knowledge)

**Comment by JaggerJo** [comment]
@melursus23 merged 👌 thanks for the contribution.
