### ISSUE TITLE
Errors when compiling "Getting Started - FuncUI" example

### ISSUE THREAD

**Issue by jcoder58** [fsprojects/Avalonia.FuncUI#297]
The following compile errors happen when I try to build the example code on [Getting Started - FuncUI](https://funcui.avaloniaui.net/). The only difference is I'm trying this from a Visual Studio F# console project instead of the command line.
```
Error	FS0193	The module/namespace 'Avalonia.Controls' from compilation unit 'Avalonia.Controls' did not contain the namespace, module or type 'ItemsRepeater'	FuncUISample	C:\Users\***\source\repos\FuncUISample\FuncUISample\FSC	1	N/A
Error	FS0039	The value, namespace, type or module 'DockPanel' is not defined.	FuncUISample	C:\Users\***source\repos\FuncUISample\FuncUISample\Program.fs	16	N/A```

**Comment by JaggerJo** [comment]
Hey @jcoder58 

seems like there was an issue with a preview version. I just updated the docs, the following packages should work in combination:

```xml
        <PackageReference Include="Avalonia.Desktop" Version="11.0.0-preview6" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.0-preview6" />
        <PackageReference Include="Avalonia.FuncUI" Version="0.6.0-preview9.1" />
```

**Comment by jcoder58** [comment]
That fixed the first set of errors but there is a new error

Error	FS0039	The value, constructor, namespace or type 'children' is not defined.	FuncUISample	C:\Users\***\source\repos\FuncUISample\FuncUISample\Program.fs	17	N/A

**Comment by JaggerJo** [comment]
@jcoder58 strange. Can you attache a zip file containing your project?

**Comment by jcoder58** [comment]
[FuncUISample.zip](https://github.com/fsprojects/Avalonia.FuncUI/files/11193482/FuncUISample.zip)

**Comment by JaggerJo** [comment]
Works for me after adding 2 lines (they are in the docs, guess they were marked as unused before):

```fsharp
open Avalonia.Controls // <- missing
open Avalonia.Layout // <- missing
```

**Comment by jcoder58** [comment]
That fixed it
