### ISSUE TITLE
Resize DatePicker or CalendarDatePicker

### ISSUE THREAD

**Issue by tirsomf** [fsprojects/Avalonia.FuncUI#305]
I'm starting to work with this library and I have issues when I try to resize any of the date controls. For example, if I change the width through DatePicker.width, the control is not resized correctly and I lose the left and right borders. The same when I try to change the heigh or width of the CalendarDatePicker.
My guess is that it has to be related to internal components not resizing accordingly.
Is possible to make a smaller DatePicker without loosing parts of it?

**Comment by JaggerJo** [comment]
Welcome @tirsomf,

as FuncUI is just a small layer on top of [AvaloniaUI](https://github.com/AvaloniaUI/Avalonia), so I recommend creating an issue there. 

Regardless, it would be good to include a screenshot of the clipped control and some sample code.
