### ISSUE TITLE
Getting started experience

### ISSUE THREAD

**Issue by AngelMunoz** [fsprojects/Avalonia.FuncUI#306]
Hey there, I was about to start an funcui project today and found that the templates in the repo are not available anymore and they were never put in the FuncUI NuGet Namespace 

Is there a particular reason these were removed?

While I understand adding a couple of NuGet packages in a new project is quite simple

The reasons these were added was to provide the least friction possible to get you started

**Comment by JaggerJo** [comment]
Hey 👋

Happy to add them back if they get updated.

I personally don't use templates and think getting started is easy even without one.

**Comment by AngelMunoz** [comment]
If there's no bandwidth to have them here I guess that's fine no problem, I just wanted to know

**Comment by JaggerJo** [comment]
We can definitely add them back if they get updated. When we switched to the new Package names it did not make sense to publish the outdated templates there.

**Comment by AngelMunoz** [comment]
Makes sense, I guess we can also have them outside in the meantime, I'll try to have something in a different repo, if there's demand for templates then it could be considered to bring them back in this repo
