### ISSUE TITLE
Avalonia Notifications not showing up on MainWindow.

### ISSUE THREAD

**Issue by wjrivera** [fsprojects/Avalonia.FuncUI#329]
I believe that **Avalonia.Controls.Notifications** not showing up on MainWindow, but I could be wrong.
Here is an example: [https://github.com/wjrivera/avalonia-funcui-notifications/blob/master/Program.fs](Program.fs)
```fsharp
type MainWindow() as this =
    inherit HostWindow()

    do
        base.Title <- "application"

        let topLevel = TopLevel.GetTopLevel(this)
        let windowManager = new WindowNotificationManager(topLevel)
        let notification = new Notification("Title", "Message", NotificationType.Information)
        windowManager.Show notification
                
        Elmish.Program.mkProgram (Main.init topLevel) Main.update Main.view
        ...
```

I've tried running it from the MainWindow (HostWindow) and Main itself and nothing happens.
Would like to get your opinion on the matter.
Thank you

**Comment by Numpsy** [comment]
I've never tried using it myself, but the post at https://github.com/AvaloniaUI/Avalonia/issues/5442 says that you can't open notificiations immediately after creating the manager and need to wait for it to initialize instead

**Comment by wjrivera** [comment]
In the [https://github.com/fsprojects/Avalonia.FuncUI/issues/Program.fs](Program.js) I posted above, I called the notification in 3 places, including on **Main.update**.  I would think that by then, it would be initialized.

**Comment by JaggerJo** [comment]
I'm closing this. Feel free to reopen if you still have the issue.
