### ISSUE TITLE
Updating model after async update

### ISSUE THREAD

**Issue by b0wter** [fsprojects/Avalonia.FuncUI#338]
I am currently struggling to update my main model after an async update.
Here is what I am doing to start the operation:
```
let update (msg: Msg) (model: Model) =
    ...
    | StartSynchronization ->
        let cmd = Cmd.OfTask.either retrieveRemoteDataAsync () SynchronizationFinished SynchronizationFailed
        { model with IsSyncing = true }, cmd
    ....
```
the sync itself works flawlessly but trying to use the synced data like this:
```
let update (msg: Msg) (model: Model) =
    ...
    | SynchronizationFinished data ->
        { model with Foo = data }
    ...
```
causes the program to terminate because the `model` is updated from the wrong thread.
I've tried working around this by using `Dispatcher.UIThread.InvokeAsync`:
```
let update (msg: Msg) (model: Model) =
    ...
    | StartSynchronization ->
        let uiInvoke : Func<Task<DataUpdate>> -> Task<DataUpdate> = Dispatcher.UIThread.InvokeAsync<DataUpdate>
        let task = (fun () -> Task.FromResult(data))
        let setter = fun () -> uiInvoke task
        let cmd = Cmd.OfTask.either setter () NewSynchronizationData SynchronizationFailed
        model, cmd
    | NewSynchronizationData data ->
        { model with Foo = data }
```
It feels painfully wrong but I have not figured out how to do it properly. Can you show me how to do it properly?

**Comment by JordanMarr** [comment]
You should use `Program.runWithAvaloniaSyncDispatch ()`.

See this example:
https://github.com/fsprojects/Avalonia.FuncUI/blob/d959cfe170477dda2f7719b5bb03539a99eac771/src/Examples/Elmish%20Examples/Examples.Elmish.MusicPlayer/Shell.fs#L206

**Comment by b0wter** [comment]
Thanks a lot!
