### ISSUE TITLE
Publish Templates to NuGet?

### ISSUE THREAD

**Issue by shanoaice** [fsprojects/Avalonia.FuncUI#348]
It seems like there is a template package `Avalonia.FuncUI.Template`, but I can't find it on NuGet...Is it not there because it does not work yet or?

**Comment by Numpsy** [comment]
refs #335 perhaps

**Comment by shanoaice** [comment]
Got that, I will try to pack and install them locally before they fully fixed them.

**Comment by shanoaice** [comment]
@JaggerJo Well I intend to use this in a xplat project :(
