### ISSUE TITLE
Integrate AvaloniaEdit with FuncUI

### ISSUE THREAD

**Issue by matthewcrews** [fsprojects/Avalonia.FuncUI#358]
I am trying to get the [AvaloniaEdit library](https://github.com/AvaloniaUI/AvaloniaEdit) to work with FuncUI. I wrote some code for providing an Elmish experience:

```fsharp
namespace AvaloniaEditor

open Avalonia.FuncUI.Builder
open Avalonia.FuncUI.DSL
open Avalonia.FuncUI.Types
open AvaloniaEdit

[<AutoOpen>]
module TextEditor =

    let create (attrs: IAttr<TextEditor> list): IView<TextEditor> =
        ViewBuilder.Create<TextEditor>(attrs)

    type TextEditor with

        static member width<'t when 't :> TextEditor> (value: float) : IAttr<'t> =
            AttrBuilder<'t>.CreateProperty<float>(
                property = TextEditor.WidthProperty,
                value = value,
                comparer = ValueNone
            )

        static member height<'t when 't :> TextEditor> (value: float) : IAttr<'t> =
            AttrBuilder<'t>.CreateProperty<float>(
                property = TextEditor.HeightProperty,
                value = value,
                comparer = ValueNone
            )

        static member showLineNumbers<'t when 't :> TextEditor> (value: bool) : IAttr<'t> =
            AttrBuilder<'t>.CreateProperty<bool>(
                property = TextEditor.ShowLineNumbersProperty,
                value = value,
                comparer = ValueNone
            )
```

I define the view as:

```fsharp
module AvaloniaEditor.View

open Avalonia.Controls
open Avalonia.FuncUI.DSL
open AvaloniaEditor
open AvaloniaEdit

let view (state: State) dispatch =
    DockPanel.create [
        DockPanel.children [
            Menu.view ()
            TextEditor.create [
                TextEditor.showLineNumbers true
            ]
        ]
    ]
```

When I run it, though, the editor doesn't appear. In this case, all I see is the menu. A full sample can be found in this [repo](https://github.com/matthewcrews/AvaloniaEditor).

If it's a significant amount of work, I can pay for some help.

What I expect to see is the Menu at the top and the code editor filling the rest of the screen.

Another odd thing is that JetBrains rider seems to think that using `TextEditor` is redundant in the main `view` function:

```fsharp
let view (state: State) dispatch =
    DockPanel.create [
        DockPanel.children [
            Menu.view ()
            // ↓ Rider thinks this `TextEditor` is redundant
            TextEditor.create [
                TextEditor.showLineNumbers true
            ]
        ]
    ]
```

**Comment by JaggerJo** [comment]
Hey @matthewcrews 👋 

Did you import the editor styles? (otherwise the control is not styled at all IIRC)

**Comment by jl0pd** [comment]
> Another odd thing is that JetBrains rider seems to think that using TextEditor is redundant in the main view function

It happens because you've marked `TextEditor` module with `AutoOpen`, which brings everything into scope when parent scope is open (in this case it's a namespace `AvaloniaEditor`). Remove attribute and you won't get redundant code diagnostic

**Comment by Numpsy** [comment]
> Hey @matthewcrews 👋
> 
> Did you import the editor styles? (otherwise the control is not styled at all IIRC)

I've been using it in a FuncUI application, and you do need to add a reference to the styles (e.g.)
```
avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml
```
otherwise the control doesn't display)

**Comment by matthewcrews** [comment]
I did not import the style and I am unsure how since I’m not using XAML. How do I import style into an Elmish style FuncUI app?

**Comment by matthewcrews** [comment]
Oh, I'm an idiot. I found an example in the Elmish.Presso app. Sorry for the bother. 😊

**Comment by matthewcrews** [comment]
@Numpsy Could you provide and example of what the XAML needs to look like for importing that styling? I've never used XAML so it's all confusing to me.

**Comment by JaggerJo** [comment]
> @Numpsy Could you provide and example of what the XAML needs to look like for importing that styling? I've never used XAML so it's all confusing to me.
> 
> 
> 
> I'm importing the styling using this code:
> 
> 
> 
> ```fsharp
> 
>     override this.Initialize() =
> 
>         this.Styles.Add (FluentTheme())
> 
>         this.Styles.Load "avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml"
> 
>         this.RequestedThemeVariant <- Styling.ThemeVariant.Light
> 
> ```
> 
> 
> 
> But I'm unsure of how to customize it.

That looks like it should work 🤔

Whats the problem?

**Comment by Numpsy** [comment]
> I've never used XAML so it's all confusing to me.

My knowledge of XAML is wafer thin, which is one of the reasons I like FuncUI for creating views :-)

The main reason i'm loading the styles via xaml is really because I'm publishing the app as a self contained file and it integrates better with trimming (because the Avalonia XAML compiler inserts hard references to the xaml so the trimmer won't remove them), and it also gives you compile time errors if the xaml file in question can't be loaded.

fwiw, I have an axaml file like this
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="PackageViewer.Views.App">
    <Application.Styles>
        <FluentTheme/>
        <StyleInclude Source="avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml"/>
    </Application.Styles>
</Application>
```

and then the app startup code is like
```fsharp
type App() =
    inherit Application()

    // Initialize and load all the required styling
    override this.Initialize() =
        Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(this)
```

**Comment by matthewcrews** [comment]
@Numpsy I'm asking in case I want to customize the theme or add a new TextMate syntax highlighting style. My perception is that XAML is a core technology used for much of this and I just have very littler experience using it with FuncUI.

**Comment by matthewcrews** [comment]
I'm closing this because the question has moved beyond the context of FuncUI. Thank you for the help!

**Comment by Numpsy** [comment]
> add a new TextMate syntax highlighting style

fwiw, I think the theming for text mate sharp is done in json rather than xaml, e.g.

https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Grammars/Resources/Themes
