### ISSUE TITLE
TextBox onTextChange issues with Elmish

### ISSUE THREAD

**Issue by sixilli** [fsprojects/Avalonia.FuncUI#395]
### Description
I've described the issue here https://github.com/fsprojects/Avalonia.FuncUI/discussions/389
However, I'm facing a new issue. For some reason updating a requests that has another request with the same URL, both URLs get updated when the 2nd request is selected. I'm not really sure what's causing this to happen. 

![image](https://github.com/elmish/elmish/assets/6243871/ed1a852a-77bd-4be3-8978-ca8e8e6cb580)

### Repro code
https://github.com/sixilli/funcman/tree/main/src/App

### Expected and actual results
I expect that only 1 request should get updated and switching between requests should not cause unnecessary updates. 

### Related information 

* elmish version: 4.1
* Operating system: Windows

**Comment by JaggerJo** [comment]
@sixilli are you still having this issue?

If so please provide a tiny sample so I can reproduce it. 

Btw. I've looked at the app you linked. I'd strongly recommend using immutable state values instead of mutating an array in place.
