### ISSUE TITLE
UniformGrid.columns issue

### ISSUE THREAD

**Issue by Fxplorer** [fsprojects/Avalonia.FuncUI#400]
I was trying to add a UniformGrid in a view and there is no way to add the attributes, 
```
    let view (state: State) (dispatch) : IView =
        UniformGrid.create [
            UniformGrid.columns 4
            UniformGrid.children [
            ]
        ]
```
the `columns` and the `children` both error saying they are not implemented. 
Avalonia 11.0.10
FuncUI 1.3.0

error:
`The value, constructor, namespace or type 'columns' is not defined.`

**Comment by JaggerJo** [comment]
open Acalonia.Controls.Primitives
