### ISSUE TITLE
Maintainer status

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/Avalonia.FuncUI#404]
I have been rather inactive on this project for a pretty good while, mostly because I have a handful of other projects that I actively maintain that take all of my OSS time. 

Meanwhile, I see @Numpsy being very prolific on this repo as an active contributor, and I think, “why isn’t Numpsy a maintainer?”

So, I guess I’m saying that Numpsy would be the more ideal candidate than me to have maintainer status as he is way more invested and more familiar with the codebase. And as a side bonus, it would alleviate my mild sense of guilt for not contributing in such a long time 😅).

Any thoughts or objections?

**Comment by JaggerJo** [comment]
Agreed 👍

**Comment by Numpsy** [comment]
I never know how much time I'll have to look at anything, but I am wanting to keep looking at the NativeAOT/WebAssembly situation, and have a look at the new Avalonia 11.1 preview to see what changes are going on over there.

**Comment by JaggerJo** [comment]
@Numpsy I wouldn't expect a fixed time commitment or anything. You'd just keep doing what you're doing right now, but you'd have more rights. (could merge stuff directly, ...)

But if you don't feel comfortable being added as a maintainer that's fine too. I'm grateful for work you are putting in.

**Comment by JordanMarr** [comment]
There aren't really any expectations other than meeting a guideline that fsprojects have at least two maintainers. 

It's more about the fact that you are more immersed with the codebase which is a best-case scenario. I, on the other hand, have been doing almost 100% web / Fable in my work for the last couple years, so the Avalonia space is something I'm not actively thinking about. I also maintain the Elmish.Avalonia project, but ironically, I am only using it in a C# WPF project. 😆

If you don't feel comfortable, I'm fine to stay on as a maintainer to satisfy the fsprojects guidelines. 
The only reason I was asked to be a maintainer is because Don Syme probably did a quick glance through the Issues to find names and he saw mine and asked if I would do it. But in reality, it makes more sense to have someone like you who has naturally become more deeply involved with the project over time. 

My main contribution to the project was updating to Elmish v4 with all the breaking changes it brought to subscriptions, and answering the occasional Elmish questions. Other than that, I just haven't had enough skin in the game to be involved in any meaningful way.

**Comment by Numpsy** [comment]
> @Numpsy I wouldn't expect a fixed time commitment or anything. You'd just keep doing what you're doing right now, but you'd have more rights. (could merge stuff directly, ...)
> 
> But if you don't feel comfortable being added as a maintainer that's fine too. I'm grateful for work you are putting in.

Ok, I can do that.
