### ISSUE TITLE
Custom Control's OnKeyDown event not working

### ISSUE THREAD

**Issue by Ash-Olorenshaw** [fsprojects/Avalonia.FuncUI#433]
This is very much a "help wanted" post, no issue with FuncUI itself. I'm in the process of implementing a custom control for my FuncUI Avalonia project, and have created this custom control:
``` F#
type VimTextBlock() = 
    inherit Control()

    member val caretPosition = 0 with get, set
    member val Inlines : list<TextContainer> = [] with get, set 
    
    override this.OnKeyDown(e : KeyEventArgs) = 
        printfn $"keydown" 

        match e.Key with
        | Key.Left -> this.caretPosition <- this.caretPosition - 1
        | Key.Right -> this.caretPosition <- this.caretPosition + 1 
        | _ -> ()

        this.InvalidateVisual()

    override this.Render(context : DrawingContext) = 
        let mutable x = 0.0
        let mutable y = 0.0

        let mutable currentLen = 0
        for line in this.Inlines do
            printfn "processing line"

            currentLen <- currentLen + line.text.Length
            let formattedLine = FormatContainer line

            if currentLen >= this.caretPosition then
                context.DrawLine(
                    Pen(Brushes.Black, 1.0),
                    Point(x, y),
                    Point(x, y + formattedLine.Height)
                )
            context.DrawText(formattedLine, Point(x, y))
            x <- x + formattedLine.Width
        base.Render(context)

    interface Styling.IStyleable with 
        member this.StyleKey = typeof<Control>

module VimTextBlock = 
    let create (attrs : IAttr<VimTextBlock> list): IView<VimTextBlock> = 
        ViewBuilder.Create<VimTextBlock>(attrs)
        
type VimTextBlock with 
    
    static member InlinesProperty<'t when 't :> VimTextBlock>(value: list<TextContainer>) : IAttr<'t> = 
        let getter : 't -> list<TextContainer> = (fun c -> c.Inlines)
        let setter : 't * list<TextContainer> -> unit = (fun (c, v) -> c.Inlines <- v)
        AttrBuilder<'t>.CreateProperty<list<TextContainer>>("Inlines", value,  ValueSome getter, ValueSome setter, ValueNone)

    static member CaretPositionProperty<'t when 't :> VimTextBlock>(value: int) : IAttr<'t> = 
        let getter : 't -> int = (fun c -> c.caretPosition)
        let setter : 't * int -> unit = (fun (c, v) -> c.caretPosition <- v)
        AttrBuilder<'t>.CreateProperty<int>("caretPosition", value,  ValueSome getter, ValueSome setter, ValueNone)
```

As you can probably tell the basic idea is to make a custom TextBlock style control which also has a cursor which can by moved by the keyboard. Currently however I don't seem to have any ability to receive key events - nothing seems to happen. I have tested implementing top level key events which work, but none for this specific control. 

Some code has been removed for the sake of simplifying this description, but the code removed only pertains to calculations for the caret, nothing relating to the actual keydown. Also, some of the code is currently not very functional, this is for the most part a bit of a mockup for testing some stuff before I do another pass where everything is actually written properly.

Also, if you're curious, `TextContainer` is a custom type which holds all the same values as `FormattedText` for a functionally easier way to access the information before it is eventually transformed into `FormattedText` with `FormatContainer`

Sorry in advance if I've missed something really obvious, besides some basic uses for FuncUI and Avalonia, I haven't done that much with either of them.

**Comment by JaggerJo** [comment]
I thinks your question might be answered by reading through the following issue

https://github.com/AvaloniaUI/Avalonia/discussions/12163

**Comment by Ash-Olorenshaw** [comment]
> I thinks your question might be answered by reading through the following issue
> 
> [AvaloniaUI/Avalonia#12163](https://github.com/AvaloniaUI/Avalonia/discussions/12163)

Thanks, this helped. Using
```F#
VimTextBlock.focusable true
```
when initialising the class in FuncUI worked. Still curious as to how
```
canvas.Focus();
```
which is suggested as a C# Avalonia method might be used in FuncUI to automatically focus the element, but it's pretty fine the way it is now.

**Comment by JaggerJo** [comment]
You can use effects in components to run side effects. 
You could also call at the method in an init function. 

See the docs.

**Comment by Ash-Olorenshaw** [comment]
> You can use effects in components to run side effects. You could also call at the method in an init function.
> 
> See the docs
> 
> https://funcui.avaloniaui.net/common-questions#id-1.-execute-code-on-control-creation

I don't think I perhaps understand what you're suggesting as using the init function like so:
```F#
VimTextBlock.init ( fun vimTextBlock ->
     ignore (vimTextBlock.Focus())
)
```
doesn't automatically focus the element at all. However, it is possible to solve this by putting that line inside the declaration of the class's init code like this:
```F#
override this.OnInitialized() = 
     ignore (this.Focus())
```
(all of this wrapped in `ignore` of course since init is expecting `unit` not `bool`)
