### ISSUE TITLE
Textbox.focus missing

### ISSUE THREAD

**Issue by Userlinger** [fsprojects/Avalonia.FuncUI#436]
Hi, i am really missing a way to set focus to a Textbox in the view function. Is there an obvious way to do that. 
The init function does not work in my case as i need to set the focus later on at any given time.    
Thanks!

**Comment by JaggerJo** [comment]
Check out this sample

![CleanShot 2024-09-08 at 15 00 12](https://github.com/user-attachments/assets/bfb6e41c-5633-4520-8a59-a7fc0ad23cbd)

https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Examples/Examples.SettingFocus/Program.fs

**Comment by JaggerJo** [comment]
Also added a section to the docs:

https://app.gitbook.com/o/-MXCQh7-_vDSlxde1ips/s/7f5PCouw0Xsf6SzELfv8/common-questions#managing-focus

**Comment by Userlinger** [comment]
Wow, thanks for the quick response! Is there a way to do a similar thing in the Elmish programming model as well? 
I tried caching my textboxes in a dictionary but run into issues. (i guess because that conflicts with the patching system).
 
 Btw: I think this is a super cool way to build UIs! Greatly appreciate it!

**Comment by JaggerJo** [comment]
You can do something similar in elmish, but you'll need to somewhere store/retrieve the control reference you want to focus.

I would not use elmish, but the component system instead. It makes building real world applications a lot simpler IMHO.
