### ISSUE TITLE
DataGrid Events

### ISSUE THREAD

**Issue by CoolCoderSuper** [fsprojects/Avalonia.FuncUI#440]
Most of the DataGrid events do not have bindings available.
I assume this is because RoutedEvent field for them.

What is the best way to use these events?
My initial thoughts were to use `init` but this doesn't seem to work.

```fsharp
DataGrid.init _.CellEditEnded.Add(fun _ -> context.SaveChanges() |> ignore)
```

Basically the event handler does not fire.

**Comment by JaggerJo** [comment]
With the code above you are basically using the DataGrid API directly. Are you sure the event should fire?

Can you do a test without FuncUI to assure that?

**Comment by CoolCoderSuper** [comment]
<DataGrid Grid.Row="1" Grid.Column="2" SelectionMode="Single" AutoGenerateColumns="False" CellEditEnded="Notes_OnCellEditEnded">

Yes it does fire.

**Comment by JaggerJo** [comment]
Can you create a runnable sample?

**Comment by CoolCoderSuper** [comment]
OK, nevermind I made a mistake on my part.

**Comment by CoolCoderSuper** [comment]
But is this really the best way just thinking from event attach and detach standpoint?

**Comment by JaggerJo** [comment]
Is there a routed event for it? If so we can create a binding for it.

**Comment by CoolCoderSuper** [comment]
No, I do not think there is currently.
I will make a request in Avalonia for that then
Thanks.
