### ISSUE TITLE
Themes partially loaded

### ISSUE THREAD

**Issue by Aytharn** [fsprojects/Avalonia.FuncUI#441]
Trying to use FuncUI with Semi, starting from Avalonia 11.2.x breaks up the custom apple device font loading, creating horrible artefacts on accented letters with Semi and Ursa.
For instance this is the Base.axaml file that gets ignored by FuncUI. It's not an Avalonia bug, it's FuncUI.
<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            <SolidColorBrush x:Key="DefaultForeground" Color="#1C1F23" />
        </ResourceDictionary>
        <ResourceDictionary x:Key="Dark">
            <SolidColorBrush x:Key="DefaultForeground" Color="#F9F9F9" />
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
    <x:Double x:Key="DefaultFontSize">14</x:Double>
    

> <FontFamily x:Key="DefaultFontFamily">Inter, -apple-system,BlinkMacSystemFont,PingFang SC, Microsoft YaHei, Segoe UI, Hiragino Sans GB, Helvetica Neue,Helvetica,Arial,sans-serif</FontFamily>

    <FontFamily x:Key="CodeFontFamily">Cascadia Code, Consolas, Inconsolata, monospace</FontFamily>
</ResourceDictionary>

With SukiUI the fonts are working but it can't detect Dark/Light theme configuration of the OS under macOS, neither the font inside the DataGrid (invisible text)

**Comment by JaggerJo** [comment]
Pretty sure this is not related to funcUI but Avalonia itself. 

Can you check if you run into the same issue when only using Avalonia?

**Comment by Aytharn** [comment]
I spent a whole week checking, it's due to something nasty going on within avalonia 11.2.x and FuncUI, for time being I had to revert to 11.1.5 and everything is alright.
It is connected with https://github.com/AvaloniaUI/Avalonia/issues/17527 but again, be bug arises only when using FuncUI on macOS

**Comment by JaggerJo** [comment]
Can you provide a runnable sample?

Pretty sure it's a version mismatch. FuncUI does not touch any of that..

**Comment by JaggerJo** [comment]
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/f47dc1e8-45ca-4d2b-a7f0-347b86428572">


Just checked and with the Fluent Theme there are no issues. 

Versions:
```
        <PackageReference Include="Avalonia.Desktop" Version="11.2.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.0" />
```

I'm closing this issue. I'll reopen it if you can demonstrate it's related to FuncUI.

**Comment by Aytharn** [comment]
Sorry you probably didn't read above... Why did you try Fluent? 
I said the problem is with Semi (an partially with Suki) on an Apple Platform.

**Comment by JaggerJo** [comment]
Hmm, yeah. It works perfectly with the Fluent Theme. I'd reach out to the Semi maintainers.

<img width="912" alt="image" src="https://github.com/user-attachments/assets/80e5795d-e31b-43a9-8b4e-358d3dd23d38">
