### ISSUE TITLE
Proposal to add something like reacts 'useEffect

### ISSUE THREAD

**Issue by JaggerJo** [fsprojects/Avalonia.FuncUI#68]
I thought about adding something like Reacts [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect) to simplify interop with some existing Avalonia Controls (CefGlue for Example)

```fsharp
Browser.create [
    Browser.startUrl "duckduckgo.com"
    // not sure how to trigger
    Browser.useEffect (fun browser -> browser.GoBack())
]
```

Implementing this feature is not complicated, maybe adding more 'hook' for attach und detach could also be helpful for controls that need to be specifically initialised.

Maybe effects should also be located in a new namespace like `Avalonia.FuncUI.DSL.Effects`, because they introduce side effects to an otherwise pure DSL.

@uxsoft @AngelMunoz @AngelMunoz 
opinions ?

**Comment by AngelMunoz** [comment]
I think this could solve some rough spots when interacting with stateful controls that someone could find in the wild.

However I'm not sure how can we use these within elmish by looking at the react's sample I see this
```js
import React, { useState, useEffect } from 'react';
function Example() {
  useEffect(() => {
    document.title = `You clicked ${count} times`;
  });
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

Whic I think it would translate somewhat like this in F#

```fsharp
let view state dispatch = 
  useEffect(fun _ -> window.Title <- sprintf "You clicked %i times" state.count)
  DockPanel. create [
    // the rest
  ]
```

the way I understand react uses it it's fairly easy for them because it's easy to have global things in javascript, document is the example here
when I see it in fsharp I can only think that the window (or browser in your example) reference may need to exist already or do some view query to find the element we want to use it
I'm still a bit lost in that part

**Comment by JaggerJo** [comment]
Not exactly sure why `useEffect` is required to access the document in JavaScript at all.

This would translate to this in FuncUI, accessing some global state is easy. 
```fsharp
let view state dispatch = 
    // global side effects (might not be the best way but works)
    window.Title <- sprintf "You clicked %i times" state.count

    DockPanel.create [
        // the rest
    ]
```

Whats not easy is accessing the reference of a control, because that's what `FuncUI` tries to hide from you most of the time. This makes it super easy to write pure Views and most of the time it just works. But, as you said above the are controls out there in the wild that require you to call a method on it. 

```fsharp
Browser.create [
    Browser.startUrl "duckduckgo.com"
    // not sure how to trigger
    Browser.useEffect (fun browser -> browser.GoBack())
]
```

```fsharp
MediaPlayer.create [
    MediaPlayer.filePath "song.mp3"

    // so something impure with the control
    Browser.useEffect (fun player -> 
        if player.state != state.playstate then
            match state.playstate with
            | Play -> player.Play()
            | Pause -> player.Pause()
    )
]
```

So `useEffect` basically gives us a type safe reference to its underlaying control and allows us to do something impure.

The media player example shows how the impure stuff could then be hidden away so if you encapsulate it further you don't need to know about it.

**Comment by AngelMunoz** [comment]
>Not exactly sure why useEffect is required to access the document in JavaScript at all.

It's just showcasing that you can do a mutation (hence the useEffect name) on an external element/control of the component it could have been a console.log too, it just shows that technically your component can be written in a pure functional way but allowing it to do side effects

>This would translate to this in FuncUI, accessing some global state is easy.

I thought global on a more "global" scale like if you could access things that are at namespace level "like" window it would mean it would have been defined earlier in the module. perhaps I'm just not looking it on the right direction

```fsharp
MediaPlayer.create [
    MediaPlayer.filePath "song.mp3"

    // so something impure with the control
    MediaPlayer.useEffect (fun (player: MediaPlayer) -> 
        if player.state != state.playstate then
            match state.playstate with
            | Play -> player.Play()
            | Pause -> player.Pause()
    )
]
```

Yeah I think this gives me a better insight on how could they be used, you still need to use your current state to allow it to do what you need.

That could address stateful components coming from other C# libraries indeed.
Are there any concerns about F# authored controls? 
I guess in the end even if you choose F# you still need to to the usual UserControl inheritance and property declaration thing.

**Comment by JaggerJo** [comment]
> @AngelMunoz Are there any concerns about F# authored controls?

As you already said it's the same for F# Controls.

**Comment by AngelMunoz** [comment]
Also now that I think of it what are the advantages/disadvantages to using "External Messages"
like in here
https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Content.fs#L18
https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Shell.fs#L60

in the child you expose an external command that should/could be used to trigger a different command on your child control

https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Shell.fs#L52

I found out about that approach from this [post](https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd)

**Comment by JaggerJo** [comment]
> Also now that I think of it what are the advantages/disadvantages to using "External Messages"
> like in here
> https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Content.fs#L18
> https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Shell.fs#L60
> 
> in the child you expose an external command that should/could be used to trigger a different command on your child control
> 
> https://github.com/AngelMunoz/Raznor/blob/master/Raznor.App/Shell.fs#L52
> 
> I found out about that approach from this [post](https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd)

Good post, thanks. I don't know of any disadvantages and I'm sure this works well in most cases.

**Comment by Swoorup** [comment]
Does this also allow specifying dependencies in useEffect? i,e effect will be called if any of the dependencies changes.

**Comment by JaggerJo** [comment]
@Swoorup `useEffect` allows you to do something with the actual instance of the control. I think it should be executed every time (at least by default).

**Comment by JaggerJo** [comment]
#96

**Comment by JaggerJo** [comment]
contained in PR https://github.com/fsprojects/Avalonia.FuncUI/pull/179
