### ISSUE TITLE
Question: How to do validation?

### ISSUE THREAD

**Issue by bradphelan** [fsprojects/Avalonia.FuncUI#92]
If I have a textbox that needs parsing to an int and I would like that textbox to show errors if the parsing fails this is easy to do with Avalonia proper. One just needs to set the errors property of the textbox.

However ( and forgetting about the lens stuff I'm working on ) How would you handle validation if you had the following complex domain model

```fsharp


However it is tedious to have to reflect the parsing errors into the immutable model tree. In fact the model should not be updated if if the parsing fails. This is a local failure. It feels like I should be able to do something like this in FUNCUI.

```fsharp
    type Company = {
        id: int
        name: string
        business: string
        employees: Person array
        revenue: int32
    }

    type State {
         companies Company array
         selectedCompany: int
    }
```

So there are two levels. Let's say we want to edit the ``Company.revenue field`` and this requires validation. There are two types of validation. 1 easy and 1 hard(er).

The first is validation of the ``revenue:int32`` As this is part of the data model we can just perform some validation during the view function and render some message out.

The second is parsing validation. The user should only be allowed to enter in valid integers and if they don't then a message should be displayed. However strings that don't parse to an integer can't be put in the model and won't be available on the next render pass. This means there needs to be extra storage for this error data which seems a bit tedious though maybe there is no other way.

Do you have any suggestions on this?

**Comment by bradphelan** [comment]
I have managed to come up with a neat solution. It still required the state of the text fields to be stored in the main state. But it is relatively elegant.

![2020-03-27_17-29-41](https://user-images.githubusercontent.com/17650/77778032-aec40d00-7050-11ea-9003-a85546c62535.gif)

The main body of the view is simple

```fsharp
StackPanel.create [
    StackPanel.orientation Orientation.Vertical
    StackPanel.children [
        StackPanel.create [
            StackPanel.orientation Orientation.Horizontal
            StackPanel.children [
                TextBlock.create [
                    TextBlock.text "Value0"
                    TextBlock.width 150.0
                ]
                TextBox.create [
                    yield! bindValidation value0 Parsers.int valueParse0Errors validate
                    TextBox.width 150.0
                ]
            ]
        ]
        StackPanel.create [
            StackPanel.orientation Orientation.Horizontal
            StackPanel.children [
                TextBlock.create [
                    TextBlock.text "Value1"
                    TextBlock.width 150.0
                ]
                TextBox.create [
                    yield! bindValidation value1 Parsers.int value1ParseErrors validate
                    TextBox.width 150.0
                ]
            ]
        ]

    ]
```

where 

* **value0** and **value1** are bindings ( via lenses ) to two model fields we want to update
* **value0ParseErrors** and **value1ParseErrors** are bindings (via lenses ) for the parsing errors stored in the view state

Full implementation at 

https://github.com/bradphelan/FUNCUI.Samples/blob/master/src/Examples/ValidatingTextBoxApp/Main.fs

**Comment by JaggerJo** [comment]
I'll take a look, haven't needed input validation personally. not sure how others solved it. 

If you don't need the error in the state one way to do this would be a custom control that basically has a validate function and only fires `TextChanged` if the new text is valide.. or something :)

BTW. pls. keep posting these questions, they help with upcoming documentation :)

**Comment by bradphelan** [comment]
Throwing away the error state is the easy thing. 

> If you don't need the error in the state one way to do this would be a custom control that basically has a validate function and only fires TextChanged if the new text is valide.. or something :)

Throwing away the error state is exactly what I did first when building the lens system. But that seemed like cheating. I want my textbox to tell me if I've input a pattern that cannot be parsed. I also considered writing a custom control. But that feels like cheating. So I got the two types of validation working in the simple example. The next experiment is to see how I can use this validating text box along with it's state and put this into the larger more complex master - detail view. I'm curious as to see what abstractions turn up in the final state model and if it's still possible to keep business logic state and view state cleanly seperated.

**Comment by JaggerJo** [comment]
@bradphelan revisited this because of a comment on Gitter. After using Elmish more in production I agree with you that the message types are not needed and add noise. I was wrong about that, your approach with using lenses seems to be the better one. 

Would be interesting to see how we could take this even further. There are a few thing's I don't like about the Elmish take on MVU.

**Comment by bradphelan** [comment]
@JaggerJo  Sorry. I don't really have any time at the moment. I'm focussed on other things than .NET based UI's. The company has decided to focus on HTML based UIs. However feel free to fork / steal / borrow any code from https://github.com/bradphelan/FUNCUI.Samples

**Comment by SeanU** [comment]
I have also been plugging away at validation. The solution I am working on is a bit more rough and ready than @bradphelan's, but it's suiting me for the moment. Except that have yet to get it to play nice with ItemTemplates in controls like `ListView`.

```fsharp
    type Template =
        { Name: string
          Fields: Field list }
    
    type State = {Template: Template}

    // Used to refer to identify specific items in the state.
    type Member =
        | Name
        | Field of Field

    type ValidationError =
        { Subject: Member
          Message: string }

    let private fieldTemplate (field: Field) dispatch isError =
        TextBox.create [
            TextBox.text field.Name
            TextBox.onGotFocus (
                (fun args -> dispatch (BeginEditField field)),
                OnChangeOf field
            )
            TextBox.onTextChanged (EditValueChange >> dispatch)
            TextBox.onLostFocus (fun _ -> dispatch EndEdit)
            if isError (Field field) then
                TextBox.borderBrush "Red"
        ]

     let private view state dispatch (validate: State -> ValidationError list) =
         let errors = validate state
         let isError member = 
             errors 
             |> (fun e -> e.Subject)
             |> Seq.contains member 
             
         ...
         
            ListBox.create [
                ListBox.dataItems state.Template.Fields
                ListBox.itemTemplate (
                    DataTemplateView<Field>
                        .create(fun item ->
                            fieldTemplate item dispatch isError)  // nope!
                )
                ListBox.selectionMode SelectionMode.Single
            ]
```

I flagged the problem with a "nope!" comment. The ItemTemplate is not re-created on each redraw, so the `isError` function that gets used when the item changes will always reflect the state from the first time the view was evaluated. I'm not quite sure what to do with that. I'm considering changing the `ListBox.dataItems` to a join of the fields with any associated validation errors, but something about that approach doesn't sit right with me at the moment.

Anyway, that's where I am for the moment. I can see it possibly leading to some excess boilerplate (Though, what validation scheme doesn't?), but I'm wondering if some of that can be mitigated with a type provider.

**Comment by JordanMarr** [comment]
Closing this issue because it appears to be abandoned. Feel free to reopen if needed.
